// AUTO-GENERATED by scripts/gen-preload.mjs — 勿手改。请编辑 electron/ipc/channels.mjs 后重新生成。

const { contextBridge, ipcRenderer, webUtils } = require('electron')

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args)

contextBridge.exposeInMainWorld('taskweaver', {
  backendReady: (...args) => invoke("backend:ready", ...args),
  app: {
    clearConversation: (...args) => invoke("app:clearConversation", ...args),
    deleteThread: (...args) => invoke("app:deleteThread", ...args),
    forkThread: (...args) => invoke("app:forkThread", ...args),
    getState: (...args) => invoke("app:getState", ...args),
    listOutputLogs: (...args) => invoke("app:listOutputLogs", ...args),
    listThreads: (...args) => invoke("app:listThreads", ...args),
    pickWorkspace: (...args) => invoke("app:pickWorkspace", ...args),
    renameThread: (...args) => invoke("app:renameThread", ...args),
    searchThreads: (...args) => invoke("app:searchThreads", ...args),
    setModelKey: (...args) => invoke("app:setModelKey", ...args),
    setPermissionMode: (...args) => invoke("app:setPermissionMode", ...args),
    setThinkingLevel: (...args) => invoke("app:setThinkingLevel", ...args),
    setWorkspace: (...args) => invoke("app:setWorkspace", ...args),
    switchThread: (...args) => invoke("app:switchThread", ...args),
    toggleArchiveThread: (...args) => invoke("app:toggleArchiveThread", ...args),
    togglePinThread: (...args) => invoke("app:togglePinThread", ...args)
  },
  models: {
    bridgeGetStatus: (...args) => invoke("bridge:getStatus", ...args),
    bridgeLogin: (...args) => invoke("bridge:login", ...args),
    add: (...args) => invoke("models:add", ...args),
    batchAddCustomModels: (...args) => invoke("models:batchAddCustomModels", ...args),
    cancelOAuth: (...args) => invoke("models:cancelOAuth", ...args),
    checkForUpdates: (...args) => invoke("models:checkForUpdates", ...args),
    getBusyEnterMode: (...args) => invoke("models:getBusyEnterMode", ...args),
    getThinkingLevel: (...args) => invoke("models:getThinkingLevel", ...args),
    getUpdateStatus: (...args) => invoke("models:getUpdateStatus", ...args),
    list: (...args) => invoke("models:list", ...args),
    listCustomProviders: (...args) => invoke("models:listCustomProviders", ...args),
    loadBundle: (...args) => invoke("models:loadBundle", ...args),
    logoutOAuth: (...args) => invoke("models:logoutOAuth", ...args),
    migrateLegacyOpenCodexRoutes: (...args) => invoke("models:migrateLegacyOpenCodexRoutes", ...args),
    probeProviderModels: (...args) => invoke("models:probeProviderModels", ...args),
    listProvidersAuth: (...args) => invoke("models:providersAuth", ...args),
    refresh: (...args) => invoke("models:refresh", ...args),
    remove: (...args) => invoke("models:remove", ...args),
    removeCustomProvider: (...args) => invoke("models:removeCustomProvider", ...args),
    removeProviderCredentials: (...args) => invoke("models:removeProviderCredentials", ...args),
    rollbackRegistry: (...args) => invoke("models:rollbackRegistry", ...args),
    scanLocal: (...args) => invoke("models:scanLocal", ...args),
    setActive: (...args) => invoke("models:setActive", ...args),
    setBusyEnterMode: (...args) => invoke("models:setBusyEnterMode", ...args),
    setProviderApiKey: (...args) => invoke("models:setProviderApiKey", ...args),
    setThinkingLevel: (...args) => invoke("models:setThinkingLevel", ...args),
    startOAuth: (...args) => invoke("models:startOAuth", ...args),
    submitOAuthCode: (...args) => invoke("models:submitOAuthCode", ...args),
    testCustomProvider: (...args) => invoke("models:testCustomProvider", ...args),
    testCustomProviderToolCall: (...args) => invoke("models:testCustomProviderToolCall", ...args),
    upsertCustomProvider: (...args) => invoke("models:upsertCustomProvider", ...args),
    upsertProfile: (...args) => invoke("models:upsertProfile", ...args),
    onOAuthStatus: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("models:oauthStatus", handler)
  return () => ipcRenderer.removeListener("models:oauthStatus", handler)
},
    onUpdateStatus: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("models:updateStatus", handler)
  return () => ipcRenderer.removeListener("models:updateStatus", handler)
}
  },
  openusage: {
    getLimits: (...args) => invoke("openusage:getLimits", ...args)
  },
  portfolio: {
    get: (...args) => invoke("portfolio:get", ...args),
    resetToBundled: (...args) => invoke("portfolio:resetToBundled", ...args),
    save: (...args) => invoke("portfolio:save", ...args)
  },
  pricing: {
    getStatus: (...args) => invoke("pricing:getStatus", ...args),
    sync: (...args) => invoke("pricing:sync", ...args)
  },
  usage: {
    clear: (...args) => invoke("usage:clear", ...args),
    getReport: (...args) => invoke("usage:getReport", ...args),
    getStats: (...args) => invoke("usage:getStats", ...args)
  },
  chat: {
    cancel: (...args) => invoke("chat:cancel", ...args),
    getDshView: (...args) => invoke("chat:getDshView", ...args),
    getLiveContext: (...args) => invoke("chat:getLiveContext", ...args),
    getSessionStats: (...args) => invoke("chat:getSessionStats", ...args),
    listRunningConversations: (...args) => invoke("chat:listRunningConversations", ...args),
    queueMutate: (...args) => invoke("chat:queueMutate", ...args),
    subscribeMux: (...args) => invoke("chat:subscribeMux", ...args),
    unsubscribeMux: (...args) => invoke("chat:unsubscribeMux", ...args),
    followUp: (...args) => invoke("chat:followUp", ...args),
    send: (...args) => invoke("chat:send", ...args),
    steer: (...args) => invoke("chat:steer", ...args),
    onMux: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("chat:mux", handler)
  return () => ipcRenderer.removeListener("chat:mux", handler)
},
    onDshView: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("chat:dshView", handler)
  return () => ipcRenderer.removeListener("chat:dshView", handler)
},
    onStream: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("chat:stream", handler)
  return () => ipcRenderer.removeListener("chat:stream", handler)
},
    onPromptBudget: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("chat:promptBudget", handler)
  return () => ipcRenderer.removeListener("chat:promptBudget", handler)
}
  },
  skills: {
    list: (...args) => invoke("skills:list", ...args)
  },
  tasks: {
    cancel: (...args) => invoke("tasks:cancel", ...args),
    sendMessage: (...args) => invoke("tasks:sendMessage", ...args)
  },
  github: {
    listPullRequests: (...args) => invoke("github:listPullRequests", ...args)
  },
  preferences: {
    get: (...args) => invoke("preferences:get", ...args),
    set: (...args) => invoke("preferences:set", ...args)
  },
  webSearch: {
    getConfig: (...args) => invoke("webSearch:getConfig", ...args),
    setConfig: (...args) => invoke("webSearch:setConfig", ...args),
    testSearch: (...args) => invoke("webSearch:testSearch", ...args)
  },
  jobs: {
    installLaunchAgent: (...args) => invoke("jobs:installLaunchAgent", ...args),
    list: (...args) => invoke("jobs:list", ...args),
    launchAgentInstalled: (...args) => invoke("jobs:launchAgentInstalled", ...args),
    remove: (...args) => invoke("jobs:remove", ...args),
    removeLaunchAgent: (...args) => invoke("jobs:removeLaunchAgent", ...args),
    runNow: (...args) => invoke("jobs:runNow", ...args),
    upsert: (...args) => invoke("jobs:upsert", ...args)
  },
  mcp: {
    cancelGitHubOAuth: (...args) => invoke("mcp:cancelGitHubOAuth", ...args),
    catalog: (...args) => invoke("mcp:catalog", ...args),
    configureGitHub: (...args) => invoke("mcp:configureGitHub", ...args),
    disconnect: (...args) => invoke("mcp:disconnect", ...args),
    getGitHubOAuthAvailability: (...args) => invoke("mcp:getGitHubOAuthAvailability", ...args),
    getRuntimeBinding: (...args) => invoke("mcp:getRuntimeBinding", ...args),
    installCatalog: (...args) => invoke("mcp:installCatalog", ...args),
    list: (...args) => invoke("mcp:list", ...args),
    marketplace: (...args) => invoke("mcp:marketplace", ...args),
    refresh: (...args) => invoke("mcp:refresh", ...args),
    remove: (...args) => invoke("mcp:remove", ...args),
    save: (...args) => invoke("mcp:save", ...args),
    setEnabled: (...args) => invoke("mcp:setEnabled", ...args),
    startGitHubOAuth: (...args) => invoke("mcp:startGitHubOAuth", ...args),
    testConnection: (...args) => invoke("mcp:testConnection", ...args),
    onGitHubOAuthStatus: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("mcp:githubOAuthStatus", handler)
  return () => ipcRenderer.removeListener("mcp:githubOAuthStatus", handler)
}
  },
  memory: {
    clear: (...args) => invoke("memory:clear", ...args),
    get: (...args) => invoke("memory:get", ...args)
  },
  permission: {
    addRule: (...args) => invoke("permission:addRule", ...args),
    clearRules: (...args) => invoke("permission:clearRules", ...args),
    listApprovalAudit: (...args) => invoke("permission:listApprovalAudit", ...args),
    listRules: (...args) => invoke("permission:listRules", ...args),
    removeRule: (...args) => invoke("permission:removeRule", ...args),
    respondPrompt: (...args) => invoke("permission:respondPrompt", ...args),
    onPrompt: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("permission:prompt", handler)
  return () => ipcRenderer.removeListener("permission:prompt", handler)
}
  },
  userQuestions: {
    answer: (...args) => invoke("userQuestions:answer", ...args),
    cancel: (...args) => invoke("userQuestions:cancel", ...args),
    onPrompt: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("user-question:prompt", handler)
  return () => ipcRenderer.removeListener("user-question:prompt", handler)
},
    onResolved: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("user-question:resolved", handler)
  return () => ipcRenderer.removeListener("user-question:resolved", handler)
}
  },
  sandbox: {
    getEffective: (...args) => invoke("sandbox:getEffective", ...args),
    probe: (...args) => invoke("sandbox:probe", ...args),
    setSessionMode: (...args) => invoke("sandbox:setSessionMode", ...args),
    onMode: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("sandbox:mode", handler)
  return () => ipcRenderer.removeListener("sandbox:mode", handler)
}
  },
  terminal: {
    create: (...args) => invoke("terminal:create", ...args),
    kill: (...args) => invoke("terminal:kill", ...args),
    list: (...args) => invoke("terminal:list", ...args),
    resize: (...args) => invoke("terminal:resize", ...args),
    write: (...args) => invoke("terminal:write", ...args),
    onData: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("terminal:data", handler)
  return () => ipcRenderer.removeListener("terminal:data", handler)
},
    onExit: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("terminal:exit", handler)
  return () => ipcRenderer.removeListener("terminal:exit", handler)
}
  },
  worktree: {
    applyMerge: (...args) => invoke("worktree:applyMerge", ...args),
    diff: (...args) => invoke("worktree:diff", ...args),
    list: (...args) => invoke("worktree:list", ...args),
    previewMerge: (...args) => invoke("worktree:previewMerge", ...args),
    remove: (...args) => invoke("worktree:remove", ...args)
  },
  workspace: {
    createManualGitCommit: (...args) => invoke("workspace:createManualGitCommit", ...args),
    deleteGitCheckpoint: (...args) => invoke("workspace:deleteGitCheckpoint", ...args),
    getGitCheckpointDiff: (...args) => invoke("workspace:getGitCheckpointDiff", ...args),
    gitStatus: (...args) => invoke("workspace:gitStatus", ...args),
    gitSuggestCommit: (...args) => invoke("workspace:gitSuggestCommit", ...args),
    listGitCheckpoints: (...args) => invoke("workspace:listGitCheckpoints", ...args),
    openPath: (...args) => invoke("workspace:openPath", ...args),
    previewManualGitCommit: (...args) => invoke("workspace:previewManualGitCommit", ...args),
    restoreGitCheckpoint: (...args) => invoke("workspace:restoreGitCheckpoint", ...args),
    revertDiff: (...args) => invoke("workspace:revertDiff", ...args),
    createReference: (...args) => invoke("workspace:createReference", ...args),
    getTrust: (...args) => invoke("workspace:getTrust", ...args),
    listContext: (...args) => invoke("workspace:listContext", ...args),
    saveClipboardImage: (...args) => invoke("workspace:saveClipboardImage", ...args),
    setTrust: (...args) => invoke("workspace:setTrust", ...args),
    getDroppedFilePath: (file) => webUtils.getPathForFile(file)
  }
,
  ...(process.env.TASKWEAVER_DEVTOOLS === '1' ? { debug: {
      shadowTranscript: (...args) => invoke("debug:shadowTranscript", ...args)
    } } : {})
})
