// AUTO-GENERATED by scripts/gen-preload.mjs — 勿手改。请编辑 electron/ipc/channels.mjs 后重新生成。

const { contextBridge, ipcRenderer, webUtils } = require('electron')

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args)

contextBridge.exposeInMainWorld('taskweaver', {
  backendReady: () => invoke('backend:ready'),
  app: {
    clearConversation: (options) => invoke('app:clearConversation', options),
    deleteThread: (threadId) => invoke('app:deleteThread', threadId),
    forkThread: (threadId, messageId) => invoke('app:forkThread', threadId, messageId),
    getState: () => invoke('app:getState'),
    listOutputLogs: (options) => invoke('app:listOutputLogs', options ?? {}),
    listThreads: () => invoke('app:listThreads'),
    pickWorkspace: () => invoke('app:pickWorkspace'),
    renameThread: (threadId, title) => invoke('app:renameThread', threadId, title),
    searchThreads: (query, options) => invoke('app:searchThreads', query, options),
    setModelKey: (modelKey) => invoke('app:setModelKey', modelKey),
    setPermissionMode: (mode) => invoke('app:setPermissionMode', mode),
    setThinkingLevel: (thinkingLevel) => invoke('app:setThinkingLevel', thinkingLevel),
    setWorkspace: (workspacePath) => invoke('app:setWorkspace', workspacePath),
    switchThread: (threadId) => invoke('app:switchThread', threadId),
    toggleArchiveThread: (threadId) => invoke('app:toggleArchiveThread', threadId),
    togglePinThread: (threadId) => invoke('app:togglePinThread', threadId)
  },
  models: {
    bridgeGetStatus: () => invoke('bridge:getStatus'),
    bridgeLogin: (kind) => invoke('bridge:login', kind),
    add: (modelKey) => invoke('models:add', modelKey),
    batchAddCustomModels: (payload) => invoke('models:batchAddCustomModels', payload ?? {}),
    cancelOAuth: () => invoke('models:cancelOAuth'),
    checkForUpdates: (options) => invoke('models:checkForUpdates', options ?? {}),
    getBusyEnterMode: () => invoke('models:getBusyEnterMode'),
    getThinkingLevel: () => invoke('models:getThinkingLevel'),
    getUpdateStatus: () => invoke('models:getUpdateStatus'),
    list: () => invoke('models:list'),
    listCustomProviders: () => invoke('models:listCustomProviders'),
    loadBundle: () => invoke('models:loadBundle'),
    logoutOAuth: (providerId) => invoke('models:logoutOAuth', providerId),
    migrateLegacyOpenCodexRoutes: () => invoke('models:migrateLegacyOpenCodexRoutes'),
    probeProviderModels: (payload) => invoke('models:probeProviderModels', payload ?? {}),
    listProvidersAuth: () => invoke('models:providersAuth'),
    refresh: () => invoke('models:refresh'),
    remove: (modelKey) => invoke('models:remove', modelKey),
    removeCustomProvider: (providerId) => invoke('models:removeCustomProvider', providerId),
    removeProviderCredentials: (providerId) => invoke('models:removeProviderCredentials', providerId),
    rollbackRegistry: () => invoke('models:rollbackRegistry'),
    scanLocal: () => invoke('models:scanLocal'),
    setActive: (modelKey) => invoke('models:setActive', modelKey),
    setBusyEnterMode: (mode) => invoke('models:setBusyEnterMode', mode),
    setProviderApiKey: (providerId, apiKey) => invoke('models:setProviderApiKey', providerId, apiKey),
    setThinkingLevel: (level) => invoke('models:setThinkingLevel', level),
    startOAuth: (providerId) => invoke('models:startOAuth', providerId),
    submitOAuthCode: (code) => invoke('models:submitOAuthCode', code),
    testCustomProvider: (payload) => invoke('models:testCustomProvider', payload),
    testCustomProviderToolCall: (payload) => invoke('models:testCustomProviderToolCall', payload),
    upsertCustomProvider: (payload) => invoke('models:upsertCustomProvider', payload),
    upsertProfile: (modelKey, patch) => invoke('models:upsertProfile', modelKey, patch),
    onOAuthStatus: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("models:oauthStatus", handler)
  return () => ipcRenderer.removeListener("models:oauthStatus", handler)
},
    onUpdateStatus: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("models:updateStatus", handler)
  return () => ipcRenderer.removeListener("models:updateStatus", handler)
}
  },
  openusage: {
    getLimits: (options) => invoke('openusage:getLimits', options)
  },
  portfolio: {
    get: () => invoke('portfolio:get'),
    resetToBundled: () => invoke('portfolio:resetToBundled'),
    save: (portfolio) => invoke('portfolio:save', portfolio)
  },
  pricing: {
    getStatus: () => invoke('pricing:getStatus'),
    sync: () => invoke('pricing:sync')
  },
  usage: {
    clear: () => invoke('usage:clear'),
    getReport: (query) => invoke('usage:getReport', query),
    getStats: () => invoke('usage:getStats')
  },
  chat: {
    cancel: (conversationId) => invoke('chat:cancel', conversationId ?? null),
    getDshView: (conversationId) => invoke('chat:getDshView', conversationId ?? null),
    getLiveContext: (conversationId) => invoke('chat:getLiveContext', conversationId ?? null),
    getSessionStats: (conversationId) => invoke('chat:getSessionStats', conversationId ?? null),
    listRunningConversations: () => invoke('chat:listRunningConversations'),
    queueMutate: (payload) => invoke('chat:queueMutate', payload),
    subscribeMux: (conversationId) => invoke('chat:subscribeMux', conversationId),
    unsubscribeMux: (conversationId) => invoke('chat:unsubscribeMux', conversationId),
    followUp: (text, conversationId) => invoke('chat:followUp', text, conversationId ?? null),
    send: (text, modelKey, skillName, executionModeOverride, workMode, conversationId) => invoke('chat:send', text, modelKey ?? null, skillName ?? null, executionModeOverride ?? null, workMode ?? 'code', conversationId ?? null),
    steer: (text, conversationId) => invoke('chat:steer', text, conversationId ?? null),
    onMux: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("chat:mux", handler)
  return () => ipcRenderer.removeListener("chat:mux", handler)
},
    onDshView: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("chat:dshView", handler)
  return () => ipcRenderer.removeListener("chat:dshView", handler)
},
    onStream: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("chat:stream", handler)
  return () => ipcRenderer.removeListener("chat:stream", handler)
},
    onPromptBudget: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("chat:promptBudget", handler)
  return () => ipcRenderer.removeListener("chat:promptBudget", handler)
}
  },
  skills: {
    list: () => invoke('skills:list')
  },
  tasks: {
    cancel: (taskId, conversationId) => invoke('tasks:cancel', taskId, conversationId ?? null),
    sendMessage: (taskId, text, conversationId) => invoke('tasks:sendMessage', taskId, text, conversationId ?? null)
  },
  github: {
    listPullRequests: (workspacePath) => invoke('github:listPullRequests', workspacePath ?? null)
  },
  preferences: {
    get: () => invoke('preferences:get'),
    set: (patch) => invoke('preferences:set', patch)
  },
  webSearch: {
    getConfig: () => invoke('webSearch:getConfig'),
    setConfig: (patch) => invoke('webSearch:setConfig', patch),
    testSearch: (query) => invoke('webSearch:testSearch', query)
  },
  jobs: {
    installLaunchAgent: (jobId) => invoke('jobs:installLaunchAgent', jobId),
    list: () => invoke('jobs:list'),
    launchAgentInstalled: (jobId) => invoke('jobs:launchAgentInstalled', jobId),
    remove: (jobId) => invoke('jobs:remove', jobId),
    removeLaunchAgent: (jobId) => invoke('jobs:removeLaunchAgent', jobId),
    runNow: (jobId) => invoke('jobs:runNow', jobId),
    upsert: (job) => invoke('jobs:upsert', job)
  },
  mcp: {
    cancelGitHubOAuth: () => invoke('mcp:cancelGitHubOAuth'),
    catalog: () => invoke('mcp:catalog'),
    configureGitHub: (token) => invoke('mcp:configureGitHub', token),
    disconnect: (id) => invoke('mcp:disconnect', id),
    getGitHubOAuthAvailability: () => invoke('mcp:getGitHubOAuthAvailability'),
    getRuntimeBinding: () => invoke('mcp:getRuntimeBinding'),
    installCatalog: (id, env) => invoke('mcp:installCatalog', { id, env }),
    list: () => invoke('mcp:list'),
    marketplace: () => invoke('mcp:marketplace'),
    refresh: () => invoke('mcp:refresh'),
    remove: (id) => invoke('mcp:remove', id),
    save: (server) => invoke('mcp:save', server),
    setEnabled: (id, enabled) => invoke('mcp:setEnabled', id, enabled),
    startGitHubOAuth: () => invoke('mcp:startGitHubOAuth'),
    testConnection: (id) => invoke('mcp:testConnection', id),
    onGitHubOAuthStatus: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("mcp:githubOAuthStatus", handler)
  return () => ipcRenderer.removeListener("mcp:githubOAuthStatus", handler)
}
  },
  memory: {
    clear: () => invoke('memory:clear'),
    get: () => invoke('memory:get')
  },
  permission: {
    addRule: (rule) => invoke('permission:addRule', rule),
    clearRules: (options) => invoke('permission:clearRules', options),
    listApprovalAudit: (conversationId) => invoke('permission:listApprovalAudit', conversationId ?? null),
    listRules: () => invoke('permission:listRules'),
    removeRule: (id) => invoke('permission:removeRule', id),
    respondPrompt: (id, response) => invoke('permission:respondPrompt', id, response),
    onPrompt: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("permission:prompt", handler)
  return () => ipcRenderer.removeListener("permission:prompt", handler)
}
  },
  userQuestions: {
    answer: (id, answer) => invoke('userQuestions:answer', id, answer),
    cancel: (id) => invoke('userQuestions:cancel', id),
    onPrompt: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("user-question:prompt", handler)
  return () => ipcRenderer.removeListener("user-question:prompt", handler)
},
    onResolved: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("user-question:resolved", handler)
  return () => ipcRenderer.removeListener("user-question:resolved", handler)
}
  },
  sandbox: {
    getEffective: () => invoke('sandbox:getEffective'),
    probe: () => invoke('sandbox:probe'),
    setSessionMode: (mode) => invoke('sandbox:setSessionMode', mode),
    onMode: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("sandbox:mode", handler)
  return () => ipcRenderer.removeListener("sandbox:mode", handler)
}
  },
  terminal: {
    create: (options) => invoke('terminal:create', options),
    kill: (id) => invoke('terminal:kill', { id }),
    list: () => invoke('terminal:list'),
    resize: (id, cols, rows) => invoke('terminal:resize', { id, cols, rows }),
    write: (id, data) => invoke('terminal:write', { id, data }),
    onData: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("terminal:data", handler)
  return () => ipcRenderer.removeListener("terminal:data", handler)
},
    onExit: (listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on("terminal:exit", handler)
  return () => ipcRenderer.removeListener("terminal:exit", handler)
}
  },
  worktree: {
    applyMerge: (taskId, options, conversationId, runId) => invoke('worktree:applyMerge', taskId, options ?? {}, conversationId ?? null, runId ?? null),
    diff: (taskId, conversationId, runId) => invoke('worktree:diff', taskId, conversationId ?? null, runId ?? null),
    list: (conversationId) => invoke('worktree:list', conversationId ?? null),
    previewMerge: (taskId, conversationId, runId) => invoke('worktree:previewMerge', taskId, conversationId ?? null, runId ?? null),
    remove: (taskId, force, conversationId, runId) => invoke('worktree:remove', taskId, force === true, conversationId ?? null, runId ?? null)
  },
  workspace: {
    createManualGitCommit: (options) => invoke('workspace:createManualGitCommit', options),
    deleteGitCheckpoint: (checkpointId) => invoke('workspace:deleteGitCheckpoint', checkpointId),
    getGitCheckpointDiff: (checkpointId) => invoke('workspace:getGitCheckpointDiff', checkpointId),
    gitStatus: () => invoke('workspace:gitStatus'),
    gitSuggestCommit: () => invoke('workspace:gitSuggestCommit'),
    listGitCheckpoints: () => invoke('workspace:listGitCheckpoints'),
    openPath: (relativePath) => invoke('workspace:openPath', relativePath),
    previewManualGitCommit: () => invoke('workspace:previewManualGitCommit'),
    restoreGitCheckpoint: (payload) => invoke('workspace:restoreGitCheckpoint', payload),
    revertDiff: (payload) => invoke('workspace:revertDiff', payload),
    createReference: (droppedPath) => invoke('workspace:createReference', droppedPath),
    getTrust: () => invoke('workspace:getTrust'),
    listContext: (query, limit) => invoke('workspace:listContext', query ?? '', limit ?? 100),
    saveClipboardImage: (payload) => invoke('workspace:saveClipboardImage', payload),
    setTrust: (trusted) => invoke('workspace:setTrust', trusted),
    getDroppedFilePath: (file) => webUtils.getPathForFile(file)
  }
,
  ...(process.env.TASKWEAVER_DEVTOOLS === '1' ? { debug: {
      shadowTranscript: (conversationId) => invoke('debug:shadowTranscript', conversationId ?? null)
    } } : {})
})
