/**
 * Curated MCP server templates (DSH-style registry seed, not a live marketplace).
 */
export const MCP_CATALOG = Object.freeze([
  {
    id: 'sequential-thinking',
    title: 'Sequential Thinking',
    description: 'Dynamic problem solving, multi-step structured thinking, and strategy revision via MCP.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
    category: 'devtools',
    iconKey: 'brain',
    color: '#8b5cf6',
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking',
  },
  {
    id: 'github',
    title: 'GitHub',
    description: 'Triage PRs, issues, CI workflows, and publish repository changes.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    envKeys: ['GITHUB_PERSONAL_ACCESS_TOKEN'],
    category: 'popular',
    iconKey: 'github',
    color: '#24292e',
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/github',
  },
  {
    id: 'everything',
    title: 'Everything Reference',
    description: 'Official MCP reference server demonstrating all tools, prompts, resources, and roots.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-everything'],
    category: 'devtools',
    iconKey: 'remote',
    color: '#059669',
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/everything',
  },
  {
    id: 'google-drive',
    title: 'Google Drive',
    description: 'Search, read and organize Drive files, Docs, Sheets, and Slides.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-gdrive'],
    envKeys: ['GDRIVE_CREDENTIALS'],
    category: 'popular',
    iconKey: 'drive',
    color: '#fbbc04',
  },
  {
    id: 'gitlab',
    title: 'GitLab',
    description: 'Interact with GitLab API, project repositories, issues, and merge requests.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-gitlab'],
    envKeys: ['GITLAB_PERSONAL_ACCESS_TOKEN'],
    category: 'popular',
    iconKey: 'gitlab',
    color: '#fc6d26',
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/gitlab',
  },
  {
    id: 'postgres',
    title: 'PostgreSQL',
    description: 'Query database schemas, inspect tables and execute read-only SQL queries.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postgres'],
    envKeys: ['POSTGRES_CONNECTION_STRING'],
    category: 'database',
    iconKey: 'postgres',
    color: '#336791',
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
  },
  {
    id: 'brave-search',
    title: 'Brave Search',
    description: 'High-quality web intelligence and search engine results for agents.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-brave-search'],
    envKeys: ['BRAVE_API_KEY'],
    category: 'popular',
    iconKey: 'search',
    color: '#fb542b',
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
  },
  {
    id: 'puppeteer',
    title: 'Puppeteer Browser',
    description: 'Headless browser automation, full-page screenshots, and dynamic DOM interaction.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-puppeteer'],
    category: 'devtools',
    iconKey: 'browser',
    color: '#00d8ff',
  },
  {
    id: 'filesystem',
    title: 'Filesystem',
    description: 'Secure, sandboxed read & write access to designated workspace directories.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', '/path/to/allowed'],
    category: 'devtools',
    iconKey: 'folder',
    color: '#6366f1',
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
  },
  {
    id: 'slack',
    title: 'Slack',
    description: 'Channel messaging, thread summaries, and team notification automation.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-slack'],
    envKeys: ['SLACK_BOT_TOKEN', 'SLACK_TEAM_ID'],
    category: 'popular',
    iconKey: 'slack',
    color: '#4a154b',
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/slack',
  },
  {
    id: 'memory',
    title: 'Memory Graph',
    description: 'Persistent key-value knowledge graph and memory recall across turns.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    category: 'devtools',
    iconKey: 'brain',
    color: '#a855f7',
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/memory',
  },
])

export function listMcpCatalog() {
  return MCP_CATALOG.map((entry) => ({ ...entry }))
}
