// AUTO-GENERATED by scripts/gen-ipc-types.mjs — 勿手改。

/** window.taskweaver is derived from the channel table and current API method contracts. */
export interface TaskweaverBridge {
  app: import('./app-api').TaskweaverAppApi
  backendReady: import('./app-api').TaskweaverBackendApi['backendReady']
  chat: import('./app-api').TaskweaverChatApi
  debug?: import('./app-api').TaskweaverDebugApi
  github?: import('./app-api').TaskweaverGithubApi
  jobs?: import('./app-api').TaskweaverJobsApi
  mcp: import('./app-api').TaskweaverMcpApi
  memory?: import('./app-api').TaskweaverMemoryApi
  models: import('./model-api').TaskweaverModelsApi
  openusage?: import('./app-api').TaskweaverOpenUsageApi
  permission?: import('./app-api').TaskweaverPermissionApi
  portfolio?: import('./app-api').TaskweaverPortfolioApi
  preferences?: import('./app-api').TaskweaverPreferencesApi
  pricing?: import('./app-api').TaskweaverPricingApi
  sandbox?: import('./app-api').TaskweaverSandboxApi
  skills: import('./app-api').TaskweaverSkillsApi
  tasks: import('./app-api').TaskweaverTasksApi
  terminal?: import('./app-api').TaskweaverTerminalApi
  usage?: import('./app-api').TaskweaverUsageApi
  userQuestions?: import('./app-api').TaskweaverUserQuestionsApi
  webSearch?: import('./app-api').TaskweaverWebSearchApi
  workspace: import('./app-api').TaskweaverWorkspaceApi
  worktree?: import('./app-api').TaskweaverWorktreeApi
}

declare global {
  interface Window {
    taskweaver?: TaskweaverBridge
  }
}

export {}
