// AUTO-GENERATED by scripts/gen-ipc-types.mjs — 勿手改。

/** 主进程 ipcHandle 与 preload invoke 通道（与 electron/ipc/channels.mjs 一致）。 */
export type InvokeChannel =
  | 'app:clearConversation'
  | 'app:deleteThread'
  | 'app:forkThread'
  | 'app:getState'
  | 'app:listOutputLogs'
  | 'app:listThreads'
  | 'app:pickWorkspace'
  | 'app:renameThread'
  | 'app:searchThreads'
  | 'app:setModelKey'
  | 'app:setPermissionMode'
  | 'app:setThinkingLevel'
  | 'app:setWorkspace'
  | 'app:switchThread'
  | 'app:toggleArchiveThread'
  | 'app:togglePinThread'
  | 'bridge:getStatus'
  | 'bridge:login'
  | 'chat:cancel'
  | 'chat:followUp'
  | 'chat:getDshView'
  | 'chat:getLiveContext'
  | 'chat:getSessionStats'
  | 'chat:listRunningConversations'
  | 'chat:queueMutate'
  | 'chat:send'
  | 'chat:steer'
  | 'chat:subscribeMux'
  | 'chat:unsubscribeMux'
  | 'debug:shadowTranscript'
  | 'github:listPullRequests'
  | 'jobs:installLaunchAgent'
  | 'jobs:list'
  | 'jobs:launchAgentInstalled'
  | 'jobs:remove'
  | 'jobs:removeLaunchAgent'
  | 'jobs:runNow'
  | 'jobs:upsert'
  | 'mcp:cancelGitHubOAuth'
  | 'mcp:catalog'
  | 'mcp:configureGitHub'
  | 'mcp:disconnect'
  | 'mcp:getGitHubOAuthAvailability'
  | 'mcp:getRuntimeBinding'
  | 'mcp:installCatalog'
  | 'mcp:list'
  | 'mcp:marketplace'
  | 'mcp:refresh'
  | 'mcp:remove'
  | 'mcp:save'
  | 'mcp:setEnabled'
  | 'mcp:startGitHubOAuth'
  | 'mcp:testConnection'
  | 'memory:clear'
  | 'memory:get'
  | 'models:add'
  | 'models:batchAddCustomModels'
  | 'models:cancelOAuth'
  | 'models:checkForUpdates'
  | 'models:getBusyEnterMode'
  | 'models:getThinkingLevel'
  | 'models:getUpdateStatus'
  | 'models:list'
  | 'models:listCustomProviders'
  | 'models:loadBundle'
  | 'models:logoutOAuth'
  | 'models:migrateLegacyOpenCodexRoutes'
  | 'models:probeProviderModels'
  | 'models:providersAuth'
  | 'models:refresh'
  | 'models:remove'
  | 'models:removeCustomProvider'
  | 'models:removeProviderCredentials'
  | 'models:rollbackRegistry'
  | 'models:scanLocal'
  | 'models:setActive'
  | 'models:setBusyEnterMode'
  | 'models:setProviderApiKey'
  | 'models:setThinkingLevel'
  | 'models:startOAuth'
  | 'models:submitOAuthCode'
  | 'models:testCustomProvider'
  | 'models:testCustomProviderToolCall'
  | 'models:upsertCustomProvider'
  | 'models:upsertProfile'
  | 'openusage:getLimits'
  | 'permission:addRule'
  | 'permission:clearRules'
  | 'permission:listApprovalAudit'
  | 'permission:listRules'
  | 'permission:removeRule'
  | 'permission:respondPrompt'
  | 'portfolio:get'
  | 'portfolio:resetToBundled'
  | 'portfolio:save'
  | 'preferences:get'
  | 'preferences:set'
  | 'pricing:getStatus'
  | 'pricing:sync'
  | 'sandbox:getEffective'
  | 'sandbox:probe'
  | 'sandbox:setSessionMode'
  | 'skills:list'
  | 'tasks:cancel'
  | 'tasks:sendMessage'
  | 'terminal:create'
  | 'terminal:kill'
  | 'terminal:list'
  | 'terminal:resize'
  | 'terminal:write'
  | 'usage:clear'
  | 'usage:getReport'
  | 'usage:getStats'
  | 'userQuestions:answer'
  | 'userQuestions:cancel'
  | 'webSearch:getConfig'
  | 'webSearch:setConfig'
  | 'webSearch:testSearch'
  | 'worktree:applyMerge'
  | 'worktree:diff'
  | 'worktree:list'
  | 'worktree:previewMerge'
  | 'worktree:remove'
  | 'workspace:createManualGitCommit'
  | 'workspace:createReference'
  | 'workspace:deleteGitCheckpoint'
  | 'workspace:getGitCheckpointDiff'
  | 'workspace:getTrust'
  | 'workspace:gitStatus'
  | 'workspace:gitSuggestCommit'
  | 'workspace:listContext'
  | 'workspace:listGitCheckpoints'
  | 'workspace:openPath'
  | 'workspace:previewManualGitCommit'
  | 'workspace:restoreGitCheckpoint'
  | 'workspace:revertDiff'
  | 'workspace:saveClipboardImage'
  | 'workspace:setTrust'

export const INVOKE_CHANNELS: readonly InvokeChannel[] = [
  'app:clearConversation',
  'app:deleteThread',
  'app:forkThread',
  'app:getState',
  'app:listOutputLogs',
  'app:listThreads',
  'app:pickWorkspace',
  'app:renameThread',
  'app:searchThreads',
  'app:setModelKey',
  'app:setPermissionMode',
  'app:setThinkingLevel',
  'app:setWorkspace',
  'app:switchThread',
  'app:toggleArchiveThread',
  'app:togglePinThread',
  'bridge:getStatus',
  'bridge:login',
  'chat:cancel',
  'chat:followUp',
  'chat:getDshView',
  'chat:getLiveContext',
  'chat:getSessionStats',
  'chat:listRunningConversations',
  'chat:queueMutate',
  'chat:send',
  'chat:steer',
  'chat:subscribeMux',
  'chat:unsubscribeMux',
  'debug:shadowTranscript',
  'github:listPullRequests',
  'jobs:installLaunchAgent',
  'jobs:list',
  'jobs:launchAgentInstalled',
  'jobs:remove',
  'jobs:removeLaunchAgent',
  'jobs:runNow',
  'jobs:upsert',
  'mcp:cancelGitHubOAuth',
  'mcp:catalog',
  'mcp:configureGitHub',
  'mcp:disconnect',
  'mcp:getGitHubOAuthAvailability',
  'mcp:getRuntimeBinding',
  'mcp:installCatalog',
  'mcp:list',
  'mcp:marketplace',
  'mcp:refresh',
  'mcp:remove',
  'mcp:save',
  'mcp:setEnabled',
  'mcp:startGitHubOAuth',
  'mcp:testConnection',
  'memory:clear',
  'memory:get',
  'models:add',
  'models:batchAddCustomModels',
  'models:cancelOAuth',
  'models:checkForUpdates',
  'models:getBusyEnterMode',
  'models:getThinkingLevel',
  'models:getUpdateStatus',
  'models:list',
  'models:listCustomProviders',
  'models:loadBundle',
  'models:logoutOAuth',
  'models:migrateLegacyOpenCodexRoutes',
  'models:probeProviderModels',
  'models:providersAuth',
  'models:refresh',
  'models:remove',
  'models:removeCustomProvider',
  'models:removeProviderCredentials',
  'models:rollbackRegistry',
  'models:scanLocal',
  'models:setActive',
  'models:setBusyEnterMode',
  'models:setProviderApiKey',
  'models:setThinkingLevel',
  'models:startOAuth',
  'models:submitOAuthCode',
  'models:testCustomProvider',
  'models:testCustomProviderToolCall',
  'models:upsertCustomProvider',
  'models:upsertProfile',
  'openusage:getLimits',
  'permission:addRule',
  'permission:clearRules',
  'permission:listApprovalAudit',
  'permission:listRules',
  'permission:removeRule',
  'permission:respondPrompt',
  'portfolio:get',
  'portfolio:resetToBundled',
  'portfolio:save',
  'preferences:get',
  'preferences:set',
  'pricing:getStatus',
  'pricing:sync',
  'sandbox:getEffective',
  'sandbox:probe',
  'sandbox:setSessionMode',
  'skills:list',
  'tasks:cancel',
  'tasks:sendMessage',
  'terminal:create',
  'terminal:kill',
  'terminal:list',
  'terminal:resize',
  'terminal:write',
  'usage:clear',
  'usage:getReport',
  'usage:getStats',
  'userQuestions:answer',
  'userQuestions:cancel',
  'webSearch:getConfig',
  'webSearch:setConfig',
  'webSearch:testSearch',
  'worktree:applyMerge',
  'worktree:diff',
  'worktree:list',
  'worktree:previewMerge',
  'worktree:remove',
  'workspace:createManualGitCommit',
  'workspace:createReference',
  'workspace:deleteGitCheckpoint',
  'workspace:getGitCheckpointDiff',
  'workspace:getTrust',
  'workspace:gitStatus',
  'workspace:gitSuggestCommit',
  'workspace:listContext',
  'workspace:listGitCheckpoints',
  'workspace:openPath',
  'workspace:previewManualGitCommit',
  'workspace:restoreGitCheckpoint',
  'workspace:revertDiff',
  'workspace:saveClipboardImage',
  'workspace:setTrust',
] as const
