#!/usr/bin/env node
/** Generate Electron's isolated preload bridge from the IPC contract table. */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  IPC_CHANNELS,
  PRELOAD_EVENTS,
  PRELOAD_LOCAL_METHODS,
  renderPreloadEventSubscription,
} from '../electron/ipc/channels.mjs'
import { parsePreloadApi } from './ipc-contract-utils.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const outPath = path.join(root, 'electron/preload.cjs')

function setBridgeMethod(tree, bridgePath, source) {
  const segments = bridgePath.split('.')
  if (segments.some((segment) => !/^[A-Za-z_$][\w$]*$/.test(segment))) {
    throw new Error(`gen-preload: invalid bridgePath: ${bridgePath}`)
  }
  let current = tree
  for (const segment of segments.slice(0, -1)) {
    if (current[segment] === undefined) current[segment] = {}
    if (typeof current[segment] !== 'object') throw new Error(`gen-preload: bridgePath collision at ${bridgePath}`)
    current = current[segment]
  }
  const leaf = segments.at(-1)
  if (current[leaf] !== undefined) throw new Error(`gen-preload: duplicate bridgePath: ${bridgePath}`)
  current[leaf] = source
}

function renderObject(tree, indent = 0, root = false) {
  const padding = ' '.repeat(indent)
  const childPadding = ' '.repeat(indent + 2)
  const properties = Object.entries(tree).map(([name, value]) => {
    const rendered = typeof value === 'string' ? value : renderObject(value, indent + 2)
    return `${childPadding}${name}: ${rendered}`
  })
  if (!properties.length) return '{}'
  return `${root ? '' : '{'}\n${properties.join(',\n')}\n${padding}${root ? '' : '}'}`
}

function renderPreload() {
  const invokeChannels = new Set()
  const bridgePaths = new Set()
  const tree = {}
  const invokeStub = () => undefined
  const webUtilsStub = { getPathForFile: () => '' }

  for (const entry of IPC_CHANNELS) {
    if (invokeChannels.has(entry.name)) throw new Error(`gen-preload: duplicate invoke channel: ${entry.name}`)
    invokeChannels.add(entry.name)
    if (bridgePaths.has(entry.bridgePath)) throw new Error(`gen-preload: duplicate bridgePath: ${entry.bridgePath}`)
    bridgePaths.add(entry.bridgePath)
    if (typeof entry.preloadFactory !== 'function') throw new Error(`gen-preload: missing preloadFactory for ${entry.name}`)
    const implementation = entry.preloadFactory(invokeStub)
    if (typeof implementation !== 'function') throw new Error(`gen-preload: preloadFactory must return a function for ${entry.name}`)
    setBridgeMethod(tree, entry.bridgePath, implementation.toString())
  }

  for (const entry of PRELOAD_EVENTS) {
    if (bridgePaths.has(entry.bridgePath)) throw new Error(`gen-preload: duplicate bridgePath: ${entry.bridgePath}`)
    bridgePaths.add(entry.bridgePath)
    const implementation = renderPreloadEventSubscription(entry.event)
    setBridgeMethod(tree, entry.bridgePath, implementation.toString())
  }

  for (const entry of PRELOAD_LOCAL_METHODS) {
    if (bridgePaths.has(entry.bridgePath)) throw new Error(`gen-preload: duplicate bridgePath: ${entry.bridgePath}`)
    bridgePaths.add(entry.bridgePath)
    const implementation = entry.create(webUtilsStub)
    if (typeof implementation !== 'function') throw new Error(`gen-preload: local API factory must return a function for ${entry.bridgePath}`)
    setBridgeMethod(tree, entry.bridgePath, implementation.toString())
  }

  const debug = tree.debug
  delete tree.debug
  const bridgeObject = renderObject(tree, 0, true)
  const debugSpread = debug
    ? `,\n  ...(process.env.TASKWEAVER_DEVTOOLS === '1' ? { debug: ${renderObject(debug, 4)} } : {})`
    : ''
  const generated = `// AUTO-GENERATED by scripts/gen-preload.mjs — 勿手改。请编辑 electron/ipc/channels.mjs 后重新生成。\n\nconst { contextBridge, ipcRenderer, webUtils } = require('electron')\n\nconst invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args)\n\ncontextBridge.exposeInMainWorld('taskweaver', {${bridgeObject}${debugSpread}\n})\n`

  const { invokeMethods, bridgeMethods } = parsePreloadApi(generated, 'electron/preload.cjs')
  const missing = [...invokeChannels].filter((channel) => !invokeMethods.has(channel))
  const extra = [...invokeMethods.keys()].filter((channel) => !invokeChannels.has(channel))
  const wrongPath = IPC_CHANNELS
    .filter((entry) => invokeMethods.get(entry.name) !== entry.bridgePath)
    .map((entry) => `${entry.name}: table=${entry.bridgePath}, generated=${invokeMethods.get(entry.name) ?? '<missing>'}`)
  const missingBridgePaths = [...bridgePaths].filter((bridgePath) => !bridgeMethods.has(bridgePath))
  const extraBridgePaths = [...bridgeMethods.keys()].filter((bridgePath) => !bridgePaths.has(bridgePath))
  const problems = [
    ...(missing.length ? [`missing invoke methods:\n${missing.join('\n')}`] : []),
    ...(extra.length ? [`generated unregistered invoke methods:\n${extra.join('\n')}`] : []),
    ...(wrongPath.length ? [`bridgePath mismatch:\n${wrongPath.join('\n')}`] : []),
    ...(missingBridgePaths.length ? [`missing bridgePath implementations:\n${missingBridgePaths.join('\n')}`] : []),
    ...(extraBridgePaths.length ? [`bridge paths have no contract:\n${extraBridgePaths.join('\n')}`] : []),
  ]
  if (problems.length) throw new Error(`gen-preload: ${problems.join('\n')}`)
  return generated
}

export function isGeneratedPreload(source) {
  return source === renderPreload()
}

const invokedPath = process.argv[1] ? path.resolve(process.argv[1]) : ''
if (invokedPath === fileURLToPath(import.meta.url)) {
  try {
    const next = renderPreload()
    const previous = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : ''
    if (process.argv.includes('--check')) {
      if (next !== previous) {
        console.error('gen-preload: electron/preload.cjs is stale; run node scripts/gen-preload.mjs')
        process.exitCode = 1
      } else {
        console.log('gen-preload: electron/preload.cjs is up to date')
      }
    } else if (next !== previous) {
      fs.writeFileSync(outPath, next)
      console.log('gen-preload: wrote electron/preload.cjs from electron/ipc/channels.mjs')
    } else {
      console.log('gen-preload: electron/preload.cjs already up to date')
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : error)
    process.exitCode = 1
  }
}
