#!/usr/bin/env node
/**
 * 从 electron/ipc/preload-spec.cjs 生成 electron/preload.cjs（阶段 3.2）。
 * 生成后校验 invoke 通道与 channels.mjs 一致。
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { INVOKE_CHANNELS } from '../electron/ipc/channels.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const specPath = path.join(root, 'electron/ipc/preload-spec.cjs')
const outPath = path.join(root, 'electron/preload.cjs')

const body = fs.readFileSync(specPath, 'utf8')
if (body.includes('AUTO-GENERATED')) {
  console.error('gen-preload: preload-spec.cjs 不应包含 AUTO-GENERATED 标记')
  process.exit(1)
}

const invokeChannels = [...new Set([...body.matchAll(/invoke\('([^']+)'/g)].map((m) => m[1]))].sort()
const expected = [...INVOKE_CHANNELS].sort()
const missingInSpec = expected.filter((ch) => !invokeChannels.includes(ch))
const extraInSpec = invokeChannels.filter((ch) => !expected.includes(ch))

if (missingInSpec.length || extraInSpec.length) {
  if (missingInSpec.length) {
    console.error('gen-preload: preload-spec 缺少 invoke 通道:\n', missingInSpec.join('\n'))
  }
  if (extraInSpec.length) {
    console.error('gen-preload: preload-spec 多余 invoke 通道（未列入 channels.mjs）:\n', extraInSpec.join('\n'))
  }
  process.exit(1)
}

const header = `// AUTO-GENERATED by scripts/gen-preload.mjs — 勿手改。请编辑 electron/ipc/preload-spec.cjs 后重新生成。\n\n`
const next = header + body
const previous = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : ''
if (next !== previous) {
  fs.writeFileSync(outPath, next)
  console.log('gen-preload: wrote electron/preload.cjs')
} else {
  console.log('gen-preload: electron/preload.cjs already up to date')
}
