/**
 * Main-process invoke contracts. This table owns channel identity, handler location,
 * and the renderer method/type contract. preload methods are generated directly from this table, alongside event and local APIs.
 */
const typeSchema = (reference) => ({ kind: 'typescript', reference })
const invokeGroup = (handlerModule, entries) => entries.map(([name, bridgePath, methodType, preloadFactory]) => ({
  name, direction: 'renderer-to-main/invoke',
  argsSchema: typeSchema(`Parameters<NonNullable<${methodType}>>`),
  resultSchema: typeSchema(`Awaited<ReturnType<NonNullable<${methodType}>>>`),
  handlerModule, bridgePath, preloadFactory: preloadFactory || ((invoke) => new Function('invoke', `return (...args) => invoke(${JSON.stringify(name)}, ...args)`)(invoke)),
}))

export const IPC_CHANNELS = [
  ...invokeGroup("electron/backend/register-ipc.mjs", [
    ["backend:ready", "backendReady", "import('./app-api').TaskweaverBackendApi['backendReady']"],
  ]),
  ...invokeGroup("electron/backend/ipc/register-app-ipc.mjs", [
    ["app:clearConversation", "app.clearConversation", "import('./app-api').TaskweaverAppApi['clearConversation']"],
    ["app:deleteThread", "app.deleteThread", "import('./app-api').TaskweaverAppApi['deleteThread']"],
    ["app:forkThread", "app.forkThread", "import('./app-api').TaskweaverAppApi['forkThread']"],
    ["app:getState", "app.getState", "import('./app-api').TaskweaverAppApi['getState']"],
    ["app:listOutputLogs", "app.listOutputLogs", "import('./app-api').TaskweaverAppApi['listOutputLogs']"],
    ["app:listThreads", "app.listThreads", "import('./app-api').TaskweaverAppApi['listThreads']"],
    ["app:pickWorkspace", "app.pickWorkspace", "import('./app-api').TaskweaverAppApi['pickWorkspace']"],
    ["app:renameThread", "app.renameThread", "import('./app-api').TaskweaverAppApi['renameThread']"],
    ["app:searchThreads", "app.searchThreads", "import('./app-api').TaskweaverAppApi['searchThreads']"],
    ["app:setModelKey", "app.setModelKey", "import('./app-api').TaskweaverAppApi['setModelKey']"],
    ["app:setPermissionMode", "app.setPermissionMode", "import('./app-api').TaskweaverAppApi['setPermissionMode']"],
    ["app:setThinkingLevel", "app.setThinkingLevel", "import('./app-api').TaskweaverAppApi['setThinkingLevel']"],
    ["app:setWorkspace", "app.setWorkspace", "import('./app-api').TaskweaverAppApi['setWorkspace']"],
    ["app:switchThread", "app.switchThread", "import('./app-api').TaskweaverAppApi['switchThread']"],
    ["app:toggleArchiveThread", "app.toggleArchiveThread", "import('./app-api').TaskweaverAppApi['toggleArchiveThread']"],
    ["app:togglePinThread", "app.togglePinThread", "import('./app-api').TaskweaverAppApi['togglePinThread']"],
  ]),
  ...invokeGroup("electron/backend/ipc/register-models-ipc.mjs", [
    ["bridge:getStatus", "models.bridgeGetStatus", "import('./model-api').TaskweaverModelsApi['bridgeGetStatus']"],
    ["bridge:login", "models.bridgeLogin", "import('./model-api').TaskweaverModelsApi['bridgeLogin']"],
    ["models:add", "models.add", "import('./model-api').TaskweaverModelsApi['add']"],
    ["models:batchAddCustomModels", "models.batchAddCustomModels", "import('./model-api').TaskweaverModelsApi['batchAddCustomModels']"],
    ["models:cancelOAuth", "models.cancelOAuth", "import('./model-api').TaskweaverModelsApi['cancelOAuth']"],
    ["models:checkForUpdates", "models.checkForUpdates", "import('./model-api').TaskweaverModelsApi['checkForUpdates']"],
    ["models:getBusyEnterMode", "models.getBusyEnterMode", "import('./model-api').TaskweaverModelsApi['getBusyEnterMode']"],
    ["models:getThinkingLevel", "models.getThinkingLevel", "import('./model-api').TaskweaverModelsApi['getThinkingLevel']"],
    ["models:getUpdateStatus", "models.getUpdateStatus", "import('./model-api').TaskweaverModelsApi['getUpdateStatus']"],
    ["models:list", "models.list", "import('./model-api').TaskweaverModelsApi['list']"],
    ["models:listCustomProviders", "models.listCustomProviders", "import('./model-api').TaskweaverModelsApi['listCustomProviders']"],
    ["models:loadBundle", "models.loadBundle", "import('./model-api').TaskweaverModelsApi['loadBundle']"],
    ["models:logoutOAuth", "models.logoutOAuth", "import('./model-api').TaskweaverModelsApi['logoutOAuth']"],
    ["models:migrateLegacyOpenCodexRoutes", "models.migrateLegacyOpenCodexRoutes", "import('./model-api').TaskweaverModelsApi['migrateLegacyOpenCodexRoutes']"],
    ["models:probeProviderModels", "models.probeProviderModels", "import('./model-api').TaskweaverModelsApi['probeProviderModels']"],
    ["models:providersAuth", "models.listProvidersAuth", "import('./model-api').TaskweaverModelsApi['listProvidersAuth']"],
    ["models:refresh", "models.refresh", "import('./model-api').TaskweaverModelsApi['refresh']"],
    ["models:remove", "models.remove", "import('./model-api').TaskweaverModelsApi['remove']"],
    ["models:removeCustomProvider", "models.removeCustomProvider", "import('./model-api').TaskweaverModelsApi['removeCustomProvider']"],
    ["models:removeProviderCredentials", "models.removeProviderCredentials", "import('./model-api').TaskweaverModelsApi['removeProviderCredentials']"],
    ["models:rollbackRegistry", "models.rollbackRegistry", "import('./model-api').TaskweaverModelsApi['rollbackRegistry']"],
    ["models:scanLocal", "models.scanLocal", "import('./model-api').TaskweaverModelsApi['scanLocal']"],
    ["models:setActive", "models.setActive", "import('./model-api').TaskweaverModelsApi['setActive']"],
    ["models:setBusyEnterMode", "models.setBusyEnterMode", "import('./model-api').TaskweaverModelsApi['setBusyEnterMode']"],
    ["models:setProviderApiKey", "models.setProviderApiKey", "import('./model-api').TaskweaverModelsApi['setProviderApiKey']"],
    ["models:setThinkingLevel", "models.setThinkingLevel", "import('./model-api').TaskweaverModelsApi['setThinkingLevel']"],
    ["models:startOAuth", "models.startOAuth", "import('./model-api').TaskweaverModelsApi['startOAuth']"],
    ["models:submitOAuthCode", "models.submitOAuthCode", "import('./model-api').TaskweaverModelsApi['submitOAuthCode']"],
    ["models:testCustomProvider", "models.testCustomProvider", "import('./model-api').TaskweaverModelsApi['testCustomProvider']"],
    ["models:testCustomProviderToolCall", "models.testCustomProviderToolCall", "import('./model-api').TaskweaverModelsApi['testCustomProviderToolCall']"],
    ["models:upsertCustomProvider", "models.upsertCustomProvider", "import('./model-api').TaskweaverModelsApi['upsertCustomProvider']"],
    ["models:upsertProfile", "models.upsertProfile", "import('./model-api').TaskweaverModelsApi['upsertProfile']"],
    ["openusage:getLimits", "openusage.getLimits", "import('./app-api').TaskweaverOpenUsageApi['getLimits']"],
    ["portfolio:get", "portfolio.get", "import('./app-api').TaskweaverPortfolioApi['get']"],
    ["portfolio:resetToBundled", "portfolio.resetToBundled", "import('./app-api').TaskweaverPortfolioApi['resetToBundled']"],
    ["portfolio:save", "portfolio.save", "import('./app-api').TaskweaverPortfolioApi['save']"],
    ["pricing:getStatus", "pricing.getStatus", "import('./app-api').TaskweaverPricingApi['getStatus']"],
    ["pricing:sync", "pricing.sync", "import('./app-api').TaskweaverPricingApi['sync']"],
    ["usage:clear", "usage.clear", "import('./app-api').TaskweaverUsageApi['clear']"],
    ["usage:getReport", "usage.getReport", "import('./app-api').TaskweaverUsageApi['getReport']"],
    ["usage:getStats", "usage.getStats", "import('./app-api').TaskweaverUsageApi['getStats']"],
  ]),
  ...invokeGroup("electron/backend/ipc/register-chat-ipc.mjs", [
    ["chat:cancel", "chat.cancel", "import('./app-api').TaskweaverChatApi['cancel']"],
    ["chat:getDshView", "chat.getDshView", "import('./app-api').TaskweaverChatApi['getDshView']"],
    ["chat:getLiveContext", "chat.getLiveContext", "import('./app-api').TaskweaverChatApi['getLiveContext']"],
    ["chat:getSessionStats", "chat.getSessionStats", "import('./app-api').TaskweaverChatApi['getSessionStats']"],
    ["chat:listRunningConversations", "chat.listRunningConversations", "import('./app-api').TaskweaverChatApi['listRunningConversations']"],
    ["chat:queueMutate", "chat.queueMutate", "import('./app-api').TaskweaverChatApi['queueMutate']"],
    ["chat:subscribeMux", "chat.subscribeMux", "import('./app-api').TaskweaverChatApi['subscribeMux']"],
    ["chat:unsubscribeMux", "chat.unsubscribeMux", "import('./app-api').TaskweaverChatApi['unsubscribeMux']"],
    ["skills:list", "skills.list", "import('./app-api').TaskweaverSkillsApi['list']"],
    ["tasks:cancel", "tasks.cancel", "import('./app-api').TaskweaverTasksApi['cancel']"],
    ["tasks:sendMessage", "tasks.sendMessage", "import('./app-api').TaskweaverTasksApi['sendMessage']"],
  ]),
  ...invokeGroup("electron/backend/ipc/register-chat-send-ipc.mjs", [
    ["chat:followUp", "chat.followUp", "import('./app-api').TaskweaverChatApi['followUp']"],
    ["chat:send", "chat.send", "import('./app-api').TaskweaverChatApi['send']"],
    ["chat:steer", "chat.steer", "import('./app-api').TaskweaverChatApi['steer']"],
  ]),
  ...invokeGroup("electron/backend/ipc/register-debug-ipc.mjs", [
    ["debug:shadowTranscript", "debug.shadowTranscript", "import('./app-api').TaskweaverDebugApi['shadowTranscript']"],
  ]),
  ...invokeGroup("electron/backend/ipc/register-preferences-ipc.mjs", [
    ["github:listPullRequests", "github.listPullRequests", "import('./app-api').TaskweaverGithubApi['listPullRequests']"],
    ["preferences:get", "preferences.get", "import('./app-api').TaskweaverPreferencesApi['get']"],
    ["preferences:set", "preferences.set", "import('./app-api').TaskweaverPreferencesApi['set']"],
    ["webSearch:getConfig", "webSearch.getConfig", "import('./app-api').TaskweaverWebSearchApi['getConfig']"],
    ["webSearch:setConfig", "webSearch.setConfig", "import('./app-api').TaskweaverWebSearchApi['setConfig']"],
    ["webSearch:testSearch", "webSearch.testSearch", "import('./app-api').TaskweaverWebSearchApi['testSearch']"],
  ]),
  ...invokeGroup("electron/backend/register-scheduled-jobs-ipc.mjs", [
    ["jobs:installLaunchAgent", "jobs.installLaunchAgent", "import('./app-api').TaskweaverJobsApi['installLaunchAgent']"],
    ["jobs:list", "jobs.list", "import('./app-api').TaskweaverJobsApi['list']"],
    ["jobs:launchAgentInstalled", "jobs.launchAgentInstalled", "import('./app-api').TaskweaverJobsApi['launchAgentInstalled']"],
    ["jobs:remove", "jobs.remove", "import('./app-api').TaskweaverJobsApi['remove']"],
    ["jobs:removeLaunchAgent", "jobs.removeLaunchAgent", "import('./app-api').TaskweaverJobsApi['removeLaunchAgent']"],
    ["jobs:runNow", "jobs.runNow", "import('./app-api').TaskweaverJobsApi['runNow']"],
    ["jobs:upsert", "jobs.upsert", "import('./app-api').TaskweaverJobsApi['upsert']"],
  ]),
  ...invokeGroup("electron/backend/ipc/register-mcp-ipc.mjs", [
    ["mcp:cancelGitHubOAuth", "mcp.cancelGitHubOAuth", "import('./app-api').TaskweaverMcpApi['cancelGitHubOAuth']"],
    ["mcp:catalog", "mcp.catalog", "import('./app-api').TaskweaverMcpApi['catalog']"],
    ["mcp:configureGitHub", "mcp.configureGitHub", "import('./app-api').TaskweaverMcpApi['configureGitHub']"],
    ["mcp:disconnect", "mcp.disconnect", "import('./app-api').TaskweaverMcpApi['disconnect']"],
    ["mcp:getGitHubOAuthAvailability", "mcp.getGitHubOAuthAvailability", "import('./app-api').TaskweaverMcpApi['getGitHubOAuthAvailability']"],
    ["mcp:getRuntimeBinding", "mcp.getRuntimeBinding", "import('./app-api').TaskweaverMcpApi['getRuntimeBinding']"],
    ["mcp:installCatalog", "mcp.installCatalog", "import('./app-api').TaskweaverMcpApi['installCatalog']"],
    ["mcp:list", "mcp.list", "import('./app-api').TaskweaverMcpApi['list']"],
    ["mcp:marketplace", "mcp.marketplace", "import('./app-api').TaskweaverMcpApi['marketplace']"],
    ["mcp:refresh", "mcp.refresh", "import('./app-api').TaskweaverMcpApi['refresh']"],
    ["mcp:remove", "mcp.remove", "import('./app-api').TaskweaverMcpApi['remove']"],
    ["mcp:save", "mcp.save", "import('./app-api').TaskweaverMcpApi['save']"],
    ["mcp:setEnabled", "mcp.setEnabled", "import('./app-api').TaskweaverMcpApi['setEnabled']"],
    ["mcp:startGitHubOAuth", "mcp.startGitHubOAuth", "import('./app-api').TaskweaverMcpApi['startGitHubOAuth']"],
    ["mcp:testConnection", "mcp.testConnection", "import('./app-api').TaskweaverMcpApi['testConnection']"],
  ]),
  ...invokeGroup("electron/backend/ipc/register-memory-ipc.mjs", [
    ["memory:clear", "memory.clear", "import('./app-api').TaskweaverMemoryApi['clear']"],
    ["memory:get", "memory.get", "import('./app-api').TaskweaverMemoryApi['get']"],
  ]),
  ...invokeGroup("electron/backend/ipc/register-permissions-ipc.mjs", [
    ["permission:addRule", "permission.addRule", "import('./app-api').TaskweaverPermissionApi['addRule']"],
    ["permission:clearRules", "permission.clearRules", "import('./app-api').TaskweaverPermissionApi['clearRules']"],
    ["permission:listApprovalAudit", "permission.listApprovalAudit", "import('./app-api').TaskweaverPermissionApi['listApprovalAudit']"],
    ["permission:listRules", "permission.listRules", "import('./app-api').TaskweaverPermissionApi['listRules']"],
    ["permission:removeRule", "permission.removeRule", "import('./app-api').TaskweaverPermissionApi['removeRule']"],
    ["permission:respondPrompt", "permission.respondPrompt", "import('./app-api').TaskweaverPermissionApi['respondPrompt']"],
    ["userQuestions:answer", "userQuestions.answer", "import('./app-api').TaskweaverUserQuestionsApi['answer']"],
    ["userQuestions:cancel", "userQuestions.cancel", "import('./app-api').TaskweaverUserQuestionsApi['cancel']"],
  ]),
  ...invokeGroup("electron/backend/ipc/register-sandbox-ipc.mjs", [
    ["sandbox:getEffective", "sandbox.getEffective", "import('./app-api').TaskweaverSandboxApi['getEffective']"],
    ["sandbox:probe", "sandbox.probe", "import('./app-api').TaskweaverSandboxApi['probe']"],
    ["sandbox:setSessionMode", "sandbox.setSessionMode", "import('./app-api').TaskweaverSandboxApi['setSessionMode']"],
  ]),
  ...invokeGroup("electron/backend/register-terminal-ipc.mjs", [
    ["terminal:create", "terminal.create", "import('./app-api').TaskweaverTerminalApi['create']"],
    ["terminal:kill", "terminal.kill", "import('./app-api').TaskweaverTerminalApi['kill']"],
    ["terminal:list", "terminal.list", "import('./app-api').TaskweaverTerminalApi['list']"],
    ["terminal:resize", "terminal.resize", "import('./app-api').TaskweaverTerminalApi['resize']"],
    ["terminal:write", "terminal.write", "import('./app-api').TaskweaverTerminalApi['write']"],
  ]),
  ...invokeGroup("electron/backend/ipc/register-worktree-ipc.mjs", [
    ["worktree:applyMerge", "worktree.applyMerge", "import('./app-api').TaskweaverWorktreeApi['applyMerge']"],
    ["worktree:diff", "worktree.diff", "import('./app-api').TaskweaverWorktreeApi['diff']"],
    ["worktree:list", "worktree.list", "import('./app-api').TaskweaverWorktreeApi['list']"],
    ["worktree:previewMerge", "worktree.previewMerge", "import('./app-api').TaskweaverWorktreeApi['previewMerge']"],
    ["worktree:remove", "worktree.remove", "import('./app-api').TaskweaverWorktreeApi['remove']"],
  ]),
  ...invokeGroup("electron/backend/register-workspace-git-ipc.mjs", [
    ["workspace:createManualGitCommit", "workspace.createManualGitCommit", "import('./app-api').TaskweaverWorkspaceApi['createManualGitCommit']"],
    ["workspace:deleteGitCheckpoint", "workspace.deleteGitCheckpoint", "import('./app-api').TaskweaverWorkspaceApi['deleteGitCheckpoint']"],
    ["workspace:getGitCheckpointDiff", "workspace.getGitCheckpointDiff", "import('./app-api').TaskweaverWorkspaceApi['getGitCheckpointDiff']"],
    ["workspace:gitStatus", "workspace.gitStatus", "import('./app-api').TaskweaverWorkspaceApi['gitStatus']"],
    ["workspace:gitSuggestCommit", "workspace.gitSuggestCommit", "import('./app-api').TaskweaverWorkspaceApi['gitSuggestCommit']"],
    ["workspace:listGitCheckpoints", "workspace.listGitCheckpoints", "import('./app-api').TaskweaverWorkspaceApi['listGitCheckpoints']"],
    ["workspace:openPath", "workspace.openPath", "import('./app-api').TaskweaverWorkspaceApi['openPath']"],
    ["workspace:previewManualGitCommit", "workspace.previewManualGitCommit", "import('./app-api').TaskweaverWorkspaceApi['previewManualGitCommit']"],
    ["workspace:restoreGitCheckpoint", "workspace.restoreGitCheckpoint", "import('./app-api').TaskweaverWorkspaceApi['restoreGitCheckpoint']"],
    ["workspace:revertDiff", "workspace.revertDiff", "import('./app-api').TaskweaverWorkspaceApi['revertDiff']"],
  ]),
  ...invokeGroup("electron/backend/ipc/register-workspace-ipc.mjs", [
    ["workspace:createReference", "workspace.createReference", "import('./app-api').TaskweaverWorkspaceApi['createReference']"],
    ["workspace:getTrust", "workspace.getTrust", "import('./app-api').TaskweaverWorkspaceApi['getTrust']"],
    ["workspace:listContext", "workspace.listContext", "import('./app-api').TaskweaverWorkspaceApi['listContext']"],
    ["workspace:saveClipboardImage", "workspace.saveClipboardImage", "import('./app-api').TaskweaverWorkspaceApi['saveClipboardImage']"],
    ["workspace:setTrust", "workspace.setTrust", "import('./app-api').TaskweaverWorkspaceApi['setTrust']"],
  ]),
]

export const INVOKE_CHANNELS = IPC_CHANNELS.map(({ name }) => name)

export const OPTIONAL_BRIDGE_NAMESPACES = Object.freeze(['pricing', 'permission', 'userQuestions', 'usage', 'openusage', 'terminal', 'portfolio', 'preferences', 'sandbox', 'webSearch', 'worktree', 'memory', 'jobs', 'github', 'debug'])


export const PRELOAD_EVENTS = Object.freeze([
  { bridgePath: 'models.onOAuthStatus', event: 'models:oauthStatus' },
  { bridgePath: 'models.onUpdateStatus', event: 'models:updateStatus' },
  { bridgePath: 'mcp.onGitHubOAuthStatus', event: 'mcp:githubOAuthStatus' },
  { bridgePath: 'chat.onMux', event: 'chat:mux' },
  { bridgePath: 'chat.onDshView', event: 'chat:dshView' },
  { bridgePath: 'chat.onStream', event: 'chat:stream' },
  { bridgePath: 'chat.onPromptBudget', event: 'chat:promptBudget' },
  { bridgePath: 'permission.onPrompt', event: 'permission:prompt' },
  { bridgePath: 'userQuestions.onPrompt', event: 'user-question:prompt' },
  { bridgePath: 'userQuestions.onResolved', event: 'user-question:resolved' },
  { bridgePath: 'terminal.onData', event: 'terminal:data' },
  { bridgePath: 'terminal.onExit', event: 'terminal:exit' },
  { bridgePath: 'sandbox.onMode', event: 'sandbox:mode' },
])

export const PRELOAD_LOCAL_METHODS = Object.freeze([
  { bridgePath: 'workspace.getDroppedFilePath', create: (webUtils) => (file) => webUtils.getPathForFile(file) },
])

export const renderPreloadEventSubscription = (event) => `(listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on(${JSON.stringify(event)}, handler)
  return () => ipcRenderer.removeListener(${JSON.stringify(event)}, handler)
}`
