/**
 * Main-process invoke contracts. This table owns channel identity, handler location,
 * and the renderer method/type contract. preload methods are generated directly from this table, alongside event and local APIs.
 */
const typeSchema = (reference) => ({ kind: 'typescript', reference })
const invokeGroup = (handlerModule, entries) => entries.map(([name, bridgePath, methodType, preloadFactory]) => ({
  name, direction: 'renderer-to-main/invoke',
  argsSchema: typeSchema(`Parameters<NonNullable<${methodType}>>`),
  resultSchema: typeSchema(`Awaited<ReturnType<NonNullable<${methodType}>>>`),
  handlerModule, bridgePath, preloadFactory,
}))

export const IPC_CHANNELS = [
  ...invokeGroup("electron/backend/register-ipc.mjs", [
    ["backend:ready", "backendReady", "import('./app-api').TaskweaverBackendApi['backendReady']", (invoke) => () => invoke('backend:ready')],
  ]),
  ...invokeGroup("electron/backend/ipc/register-app-ipc.mjs", [
    ["app:clearConversation", "app.clearConversation", "import('./app-api').TaskweaverAppApi['clearConversation']", (invoke) => (options) => invoke('app:clearConversation', options)],
    ["app:deleteThread", "app.deleteThread", "import('./app-api').TaskweaverAppApi['deleteThread']", (invoke) => (threadId) => invoke('app:deleteThread', threadId)],
    ["app:forkThread", "app.forkThread", "import('./app-api').TaskweaverAppApi['forkThread']", (invoke) => (threadId, messageId) => invoke('app:forkThread', threadId, messageId)],
    ["app:getState", "app.getState", "import('./app-api').TaskweaverAppApi['getState']", (invoke) => () => invoke('app:getState')],
    ["app:listOutputLogs", "app.listOutputLogs", "import('./app-api').TaskweaverAppApi['listOutputLogs']", (invoke) => (options) => invoke('app:listOutputLogs', options ?? {})],
    ["app:listThreads", "app.listThreads", "import('./app-api').TaskweaverAppApi['listThreads']", (invoke) => () => invoke('app:listThreads')],
    ["app:pickWorkspace", "app.pickWorkspace", "import('./app-api').TaskweaverAppApi['pickWorkspace']", (invoke) => () => invoke('app:pickWorkspace')],
    ["app:renameThread", "app.renameThread", "import('./app-api').TaskweaverAppApi['renameThread']", (invoke) => (threadId, title) => invoke('app:renameThread', threadId, title)],
    ["app:searchThreads", "app.searchThreads", "import('./app-api').TaskweaverAppApi['searchThreads']", (invoke) => (query, options) => invoke('app:searchThreads', query, options)],
    ["app:setModelKey", "app.setModelKey", "import('./app-api').TaskweaverAppApi['setModelKey']", (invoke) => (modelKey) => invoke('app:setModelKey', modelKey)],
    ["app:setPermissionMode", "app.setPermissionMode", "import('./app-api').TaskweaverAppApi['setPermissionMode']", (invoke) => (mode) => invoke('app:setPermissionMode', mode)],
    ["app:setThinkingLevel", "app.setThinkingLevel", "import('./app-api').TaskweaverAppApi['setThinkingLevel']", (invoke) => (thinkingLevel) => invoke('app:setThinkingLevel', thinkingLevel)],
    ["app:setWorkspace", "app.setWorkspace", "import('./app-api').TaskweaverAppApi['setWorkspace']", (invoke) => (workspacePath) => invoke('app:setWorkspace', workspacePath)],
    ["app:switchThread", "app.switchThread", "import('./app-api').TaskweaverAppApi['switchThread']", (invoke) => (threadId) => invoke('app:switchThread', threadId)],
    ["app:toggleArchiveThread", "app.toggleArchiveThread", "import('./app-api').TaskweaverAppApi['toggleArchiveThread']", (invoke) => (threadId) => invoke('app:toggleArchiveThread', threadId)],
    ["app:togglePinThread", "app.togglePinThread", "import('./app-api').TaskweaverAppApi['togglePinThread']", (invoke) => (threadId) => invoke('app:togglePinThread', threadId)],
  ]),
  ...invokeGroup("electron/backend/ipc/register-models-ipc.mjs", [
    ["bridge:getStatus", "models.bridgeGetStatus", "import('./model-api').TaskweaverModelsApi['bridgeGetStatus']", (invoke) => () => invoke('bridge:getStatus')],
    ["bridge:login", "models.bridgeLogin", "import('./model-api').TaskweaverModelsApi['bridgeLogin']", (invoke) => (kind) => invoke('bridge:login', kind)],
    ["models:add", "models.add", "import('./model-api').TaskweaverModelsApi['add']", (invoke) => (modelKey) => invoke('models:add', modelKey)],
    ["models:batchAddCustomModels", "models.batchAddCustomModels", "import('./model-api').TaskweaverModelsApi['batchAddCustomModels']", (invoke) => (payload) => invoke('models:batchAddCustomModels', payload ?? {})],
    ["models:cancelOAuth", "models.cancelOAuth", "import('./model-api').TaskweaverModelsApi['cancelOAuth']", (invoke) => () => invoke('models:cancelOAuth')],
    ["models:checkForUpdates", "models.checkForUpdates", "import('./model-api').TaskweaverModelsApi['checkForUpdates']", (invoke) => (options) => invoke('models:checkForUpdates', options ?? {})],
    ["models:getBusyEnterMode", "models.getBusyEnterMode", "import('./model-api').TaskweaverModelsApi['getBusyEnterMode']", (invoke) => () => invoke('models:getBusyEnterMode')],
    ["models:getThinkingLevel", "models.getThinkingLevel", "import('./model-api').TaskweaverModelsApi['getThinkingLevel']", (invoke) => () => invoke('models:getThinkingLevel')],
    ["models:getUpdateStatus", "models.getUpdateStatus", "import('./model-api').TaskweaverModelsApi['getUpdateStatus']", (invoke) => () => invoke('models:getUpdateStatus')],
    ["models:list", "models.list", "import('./model-api').TaskweaverModelsApi['list']", (invoke) => () => invoke('models:list')],
    ["models:listCustomProviders", "models.listCustomProviders", "import('./model-api').TaskweaverModelsApi['listCustomProviders']", (invoke) => () => invoke('models:listCustomProviders')],
    ["models:loadBundle", "models.loadBundle", "import('./model-api').TaskweaverModelsApi['loadBundle']", (invoke) => () => invoke('models:loadBundle')],
    ["models:logoutOAuth", "models.logoutOAuth", "import('./model-api').TaskweaverModelsApi['logoutOAuth']", (invoke) => (providerId) => invoke('models:logoutOAuth', providerId)],
    ["models:migrateLegacyOpenCodexRoutes", "models.migrateLegacyOpenCodexRoutes", "import('./model-api').TaskweaverModelsApi['migrateLegacyOpenCodexRoutes']", (invoke) => () => invoke('models:migrateLegacyOpenCodexRoutes')],
    ["models:probeProviderModels", "models.probeProviderModels", "import('./model-api').TaskweaverModelsApi['probeProviderModels']", (invoke) => (payload) => invoke('models:probeProviderModels', payload ?? {})],
    ["models:providersAuth", "models.listProvidersAuth", "import('./model-api').TaskweaverModelsApi['listProvidersAuth']", (invoke) => () => invoke('models:providersAuth')],
    ["models:refresh", "models.refresh", "import('./model-api').TaskweaverModelsApi['refresh']", (invoke) => () => invoke('models:refresh')],
    ["models:remove", "models.remove", "import('./model-api').TaskweaverModelsApi['remove']", (invoke) => (modelKey) => invoke('models:remove', modelKey)],
    ["models:removeCustomProvider", "models.removeCustomProvider", "import('./model-api').TaskweaverModelsApi['removeCustomProvider']", (invoke) => (providerId) => invoke('models:removeCustomProvider', providerId)],
    ["models:removeProviderCredentials", "models.removeProviderCredentials", "import('./model-api').TaskweaverModelsApi['removeProviderCredentials']", (invoke) => (providerId) => invoke('models:removeProviderCredentials', providerId)],
    ["models:rollbackRegistry", "models.rollbackRegistry", "import('./model-api').TaskweaverModelsApi['rollbackRegistry']", (invoke) => () => invoke('models:rollbackRegistry')],
    ["models:scanLocal", "models.scanLocal", "import('./model-api').TaskweaverModelsApi['scanLocal']", (invoke) => () => invoke('models:scanLocal')],
    ["models:setActive", "models.setActive", "import('./model-api').TaskweaverModelsApi['setActive']", (invoke) => (modelKey) => invoke('models:setActive', modelKey)],
    ["models:setBusyEnterMode", "models.setBusyEnterMode", "import('./model-api').TaskweaverModelsApi['setBusyEnterMode']", (invoke) => (mode) => invoke('models:setBusyEnterMode', mode)],
    ["models:setProviderApiKey", "models.setProviderApiKey", "import('./model-api').TaskweaverModelsApi['setProviderApiKey']", (invoke) => (providerId, apiKey) => invoke('models:setProviderApiKey', providerId, apiKey)],
    ["models:setThinkingLevel", "models.setThinkingLevel", "import('./model-api').TaskweaverModelsApi['setThinkingLevel']", (invoke) => (level) => invoke('models:setThinkingLevel', level)],
    ["models:startOAuth", "models.startOAuth", "import('./model-api').TaskweaverModelsApi['startOAuth']", (invoke) => (providerId) => invoke('models:startOAuth', providerId)],
    ["models:submitOAuthCode", "models.submitOAuthCode", "import('./model-api').TaskweaverModelsApi['submitOAuthCode']", (invoke) => (code) => invoke('models:submitOAuthCode', code)],
    ["models:testCustomProvider", "models.testCustomProvider", "import('./model-api').TaskweaverModelsApi['testCustomProvider']", (invoke) => (payload) => invoke('models:testCustomProvider', payload)],
    ["models:testCustomProviderToolCall", "models.testCustomProviderToolCall", "import('./model-api').TaskweaverModelsApi['testCustomProviderToolCall']", (invoke) => (payload) => invoke('models:testCustomProviderToolCall', payload)],
    ["models:upsertCustomProvider", "models.upsertCustomProvider", "import('./model-api').TaskweaverModelsApi['upsertCustomProvider']", (invoke) => (payload) => invoke('models:upsertCustomProvider', payload)],
    ["models:upsertProfile", "models.upsertProfile", "import('./model-api').TaskweaverModelsApi['upsertProfile']", (invoke) => (modelKey, patch) => invoke('models:upsertProfile', modelKey, patch)],
    ["openusage:getLimits", "openusage.getLimits", "import('./app-api').TaskweaverOpenUsageApi['getLimits']", (invoke) => (options) => invoke('openusage:getLimits', options)],
    ["portfolio:get", "portfolio.get", "import('./app-api').TaskweaverPortfolioApi['get']", (invoke) => () => invoke('portfolio:get')],
    ["portfolio:resetToBundled", "portfolio.resetToBundled", "import('./app-api').TaskweaverPortfolioApi['resetToBundled']", (invoke) => () => invoke('portfolio:resetToBundled')],
    ["portfolio:save", "portfolio.save", "import('./app-api').TaskweaverPortfolioApi['save']", (invoke) => (portfolio) => invoke('portfolio:save', portfolio)],
    ["pricing:getStatus", "pricing.getStatus", "import('./app-api').TaskweaverPricingApi['getStatus']", (invoke) => () => invoke('pricing:getStatus')],
    ["pricing:sync", "pricing.sync", "import('./app-api').TaskweaverPricingApi['sync']", (invoke) => () => invoke('pricing:sync')],
    ["usage:clear", "usage.clear", "import('./app-api').TaskweaverUsageApi['clear']", (invoke) => () => invoke('usage:clear')],
    ["usage:getReport", "usage.getReport", "import('./app-api').TaskweaverUsageApi['getReport']", (invoke) => (query) => invoke('usage:getReport', query)],
    ["usage:getStats", "usage.getStats", "import('./app-api').TaskweaverUsageApi['getStats']", (invoke) => () => invoke('usage:getStats')],
  ]),
  ...invokeGroup("electron/backend/ipc/register-chat-ipc.mjs", [
    ["chat:cancel", "chat.cancel", "import('./app-api').TaskweaverChatApi['cancel']", (invoke) => (conversationId) => invoke('chat:cancel', conversationId ?? null)],
    ["chat:getDshView", "chat.getDshView", "import('./app-api').TaskweaverChatApi['getDshView']", (invoke) => (conversationId) => invoke('chat:getDshView', conversationId ?? null)],
    ["chat:getLiveContext", "chat.getLiveContext", "import('./app-api').TaskweaverChatApi['getLiveContext']", (invoke) => (conversationId) => invoke('chat:getLiveContext', conversationId ?? null)],
    ["chat:getSessionStats", "chat.getSessionStats", "import('./app-api').TaskweaverChatApi['getSessionStats']", (invoke) => (conversationId) => invoke('chat:getSessionStats', conversationId ?? null)],
    ["chat:listRunningConversations", "chat.listRunningConversations", "import('./app-api').TaskweaverChatApi['listRunningConversations']", (invoke) => () => invoke('chat:listRunningConversations')],
    ["chat:queueMutate", "chat.queueMutate", "import('./app-api').TaskweaverChatApi['queueMutate']", (invoke) => (payload) => invoke('chat:queueMutate', payload)],
    ["chat:subscribeMux", "chat.subscribeMux", "import('./app-api').TaskweaverChatApi['subscribeMux']", (invoke) => (conversationId) => invoke('chat:subscribeMux', conversationId)],
    ["chat:unsubscribeMux", "chat.unsubscribeMux", "import('./app-api').TaskweaverChatApi['unsubscribeMux']", (invoke) => (conversationId) => invoke('chat:unsubscribeMux', conversationId)],
    ["skills:list", "skills.list", "import('./app-api').TaskweaverSkillsApi['list']", (invoke) => () => invoke('skills:list')],
    ["tasks:cancel", "tasks.cancel", "import('./app-api').TaskweaverTasksApi['cancel']", (invoke) => (taskId, conversationId) => invoke('tasks:cancel', taskId, conversationId ?? null)],
    ["tasks:sendMessage", "tasks.sendMessage", "import('./app-api').TaskweaverTasksApi['sendMessage']", (invoke) => (taskId, text, conversationId) => invoke('tasks:sendMessage', taskId, text, conversationId ?? null)],
  ]),
  ...invokeGroup("electron/backend/ipc/register-chat-send-ipc.mjs", [
    ["chat:followUp", "chat.followUp", "import('./app-api').TaskweaverChatApi['followUp']", (invoke) => (text, conversationId) => invoke('chat:followUp', text, conversationId ?? null)],
    ["chat:send", "chat.send", "import('./app-api').TaskweaverChatApi['send']", (invoke) => (text, modelKey, skillName, executionModeOverride, workMode, conversationId) => invoke('chat:send', text, modelKey ?? null, skillName ?? null, executionModeOverride ?? null, workMode ?? 'code', conversationId ?? null)],
    ["chat:steer", "chat.steer", "import('./app-api').TaskweaverChatApi['steer']", (invoke) => (text, conversationId) => invoke('chat:steer', text, conversationId ?? null)],
  ]),
  ...invokeGroup("electron/backend/ipc/register-debug-ipc.mjs", [
    ["debug:shadowTranscript", "debug.shadowTranscript", "import('./app-api').TaskweaverDebugApi['shadowTranscript']", (invoke) => (conversationId) => invoke('debug:shadowTranscript', conversationId ?? null)],
  ]),
  ...invokeGroup("electron/backend/ipc/register-preferences-ipc.mjs", [
    ["github:listPullRequests", "github.listPullRequests", "import('./app-api').TaskweaverGithubApi['listPullRequests']", (invoke) => (workspacePath) => invoke('github:listPullRequests', workspacePath ?? null)],
    ["preferences:get", "preferences.get", "import('./app-api').TaskweaverPreferencesApi['get']", (invoke) => () => invoke('preferences:get')],
    ["preferences:set", "preferences.set", "import('./app-api').TaskweaverPreferencesApi['set']", (invoke) => (patch) => invoke('preferences:set', patch)],
    ["webSearch:getConfig", "webSearch.getConfig", "import('./app-api').TaskweaverWebSearchApi['getConfig']", (invoke) => () => invoke('webSearch:getConfig')],
    ["webSearch:setConfig", "webSearch.setConfig", "import('./app-api').TaskweaverWebSearchApi['setConfig']", (invoke) => (patch) => invoke('webSearch:setConfig', patch)],
    ["webSearch:testSearch", "webSearch.testSearch", "import('./app-api').TaskweaverWebSearchApi['testSearch']", (invoke) => (query) => invoke('webSearch:testSearch', query)],
  ]),
  ...invokeGroup("electron/backend/register-scheduled-jobs-ipc.mjs", [
    ["jobs:installLaunchAgent", "jobs.installLaunchAgent", "import('./app-api').TaskweaverJobsApi['installLaunchAgent']", (invoke) => (jobId) => invoke('jobs:installLaunchAgent', jobId)],
    ["jobs:list", "jobs.list", "import('./app-api').TaskweaverJobsApi['list']", (invoke) => () => invoke('jobs:list')],
    ["jobs:launchAgentInstalled", "jobs.launchAgentInstalled", "import('./app-api').TaskweaverJobsApi['launchAgentInstalled']", (invoke) => (jobId) => invoke('jobs:launchAgentInstalled', jobId)],
    ["jobs:remove", "jobs.remove", "import('./app-api').TaskweaverJobsApi['remove']", (invoke) => (jobId) => invoke('jobs:remove', jobId)],
    ["jobs:removeLaunchAgent", "jobs.removeLaunchAgent", "import('./app-api').TaskweaverJobsApi['removeLaunchAgent']", (invoke) => (jobId) => invoke('jobs:removeLaunchAgent', jobId)],
    ["jobs:runNow", "jobs.runNow", "import('./app-api').TaskweaverJobsApi['runNow']", (invoke) => (jobId) => invoke('jobs:runNow', jobId)],
    ["jobs:upsert", "jobs.upsert", "import('./app-api').TaskweaverJobsApi['upsert']", (invoke) => (job) => invoke('jobs:upsert', job)],
  ]),
  ...invokeGroup("electron/backend/ipc/register-mcp-ipc.mjs", [
    ["mcp:cancelGitHubOAuth", "mcp.cancelGitHubOAuth", "import('./app-api').TaskweaverMcpApi['cancelGitHubOAuth']", (invoke) => () => invoke('mcp:cancelGitHubOAuth')],
    ["mcp:catalog", "mcp.catalog", "import('./app-api').TaskweaverMcpApi['catalog']", (invoke) => () => invoke('mcp:catalog')],
    ["mcp:configureGitHub", "mcp.configureGitHub", "import('./app-api').TaskweaverMcpApi['configureGitHub']", (invoke) => (token) => invoke('mcp:configureGitHub', token)],
    ["mcp:disconnect", "mcp.disconnect", "import('./app-api').TaskweaverMcpApi['disconnect']", (invoke) => (id) => invoke('mcp:disconnect', id)],
    ["mcp:getGitHubOAuthAvailability", "mcp.getGitHubOAuthAvailability", "import('./app-api').TaskweaverMcpApi['getGitHubOAuthAvailability']", (invoke) => () => invoke('mcp:getGitHubOAuthAvailability')],
    ["mcp:getRuntimeBinding", "mcp.getRuntimeBinding", "import('./app-api').TaskweaverMcpApi['getRuntimeBinding']", (invoke) => () => invoke('mcp:getRuntimeBinding')],
    ["mcp:installCatalog", "mcp.installCatalog", "import('./app-api').TaskweaverMcpApi['installCatalog']", (invoke) => (id, env) => invoke('mcp:installCatalog', { id, env })],
    ["mcp:list", "mcp.list", "import('./app-api').TaskweaverMcpApi['list']", (invoke) => () => invoke('mcp:list')],
    ["mcp:marketplace", "mcp.marketplace", "import('./app-api').TaskweaverMcpApi['marketplace']", (invoke) => () => invoke('mcp:marketplace')],
    ["mcp:refresh", "mcp.refresh", "import('./app-api').TaskweaverMcpApi['refresh']", (invoke) => () => invoke('mcp:refresh')],
    ["mcp:remove", "mcp.remove", "import('./app-api').TaskweaverMcpApi['remove']", (invoke) => (id) => invoke('mcp:remove', id)],
    ["mcp:save", "mcp.save", "import('./app-api').TaskweaverMcpApi['save']", (invoke) => (server) => invoke('mcp:save', server)],
    ["mcp:setEnabled", "mcp.setEnabled", "import('./app-api').TaskweaverMcpApi['setEnabled']", (invoke) => (id, enabled) => invoke('mcp:setEnabled', id, enabled)],
    ["mcp:startGitHubOAuth", "mcp.startGitHubOAuth", "import('./app-api').TaskweaverMcpApi['startGitHubOAuth']", (invoke) => () => invoke('mcp:startGitHubOAuth')],
    ["mcp:testConnection", "mcp.testConnection", "import('./app-api').TaskweaverMcpApi['testConnection']", (invoke) => (id) => invoke('mcp:testConnection', id)],
  ]),
  ...invokeGroup("electron/backend/ipc/register-memory-ipc.mjs", [
    ["memory:clear", "memory.clear", "import('./app-api').TaskweaverMemoryApi['clear']", (invoke) => () => invoke('memory:clear')],
    ["memory:get", "memory.get", "import('./app-api').TaskweaverMemoryApi['get']", (invoke) => () => invoke('memory:get')],
  ]),
  ...invokeGroup("electron/backend/ipc/register-permissions-ipc.mjs", [
    ["permission:addRule", "permission.addRule", "import('./app-api').TaskweaverPermissionApi['addRule']", (invoke) => (rule) => invoke('permission:addRule', rule)],
    ["permission:clearRules", "permission.clearRules", "import('./app-api').TaskweaverPermissionApi['clearRules']", (invoke) => (options) => invoke('permission:clearRules', options)],
    ["permission:listApprovalAudit", "permission.listApprovalAudit", "import('./app-api').TaskweaverPermissionApi['listApprovalAudit']", (invoke) => (conversationId) => invoke('permission:listApprovalAudit', conversationId ?? null)],
    ["permission:listRules", "permission.listRules", "import('./app-api').TaskweaverPermissionApi['listRules']", (invoke) => () => invoke('permission:listRules')],
    ["permission:removeRule", "permission.removeRule", "import('./app-api').TaskweaverPermissionApi['removeRule']", (invoke) => (id) => invoke('permission:removeRule', id)],
    ["permission:respondPrompt", "permission.respondPrompt", "import('./app-api').TaskweaverPermissionApi['respondPrompt']", (invoke) => (id, response) => invoke('permission:respondPrompt', id, response)],
    ["userQuestions:answer", "userQuestions.answer", "import('./app-api').TaskweaverUserQuestionsApi['answer']", (invoke) => (id, answer) => invoke('userQuestions:answer', id, answer)],
    ["userQuestions:cancel", "userQuestions.cancel", "import('./app-api').TaskweaverUserQuestionsApi['cancel']", (invoke) => (id) => invoke('userQuestions:cancel', id)],
  ]),
  ...invokeGroup("electron/backend/ipc/register-sandbox-ipc.mjs", [
    ["sandbox:getEffective", "sandbox.getEffective", "import('./app-api').TaskweaverSandboxApi['getEffective']", (invoke) => () => invoke('sandbox:getEffective')],
    ["sandbox:probe", "sandbox.probe", "import('./app-api').TaskweaverSandboxApi['probe']", (invoke) => () => invoke('sandbox:probe')],
    ["sandbox:setSessionMode", "sandbox.setSessionMode", "import('./app-api').TaskweaverSandboxApi['setSessionMode']", (invoke) => (mode) => invoke('sandbox:setSessionMode', mode)],
  ]),
  ...invokeGroup("electron/backend/register-terminal-ipc.mjs", [
    ["terminal:create", "terminal.create", "import('./app-api').TaskweaverTerminalApi['create']", (invoke) => (options) => invoke('terminal:create', options)],
    ["terminal:kill", "terminal.kill", "import('./app-api').TaskweaverTerminalApi['kill']", (invoke) => (id) => invoke('terminal:kill', { id })],
    ["terminal:list", "terminal.list", "import('./app-api').TaskweaverTerminalApi['list']", (invoke) => () => invoke('terminal:list')],
    ["terminal:resize", "terminal.resize", "import('./app-api').TaskweaverTerminalApi['resize']", (invoke) => (id, cols, rows) => invoke('terminal:resize', { id, cols, rows })],
    ["terminal:write", "terminal.write", "import('./app-api').TaskweaverTerminalApi['write']", (invoke) => (id, data) => invoke('terminal:write', { id, data })],
  ]),
  ...invokeGroup("electron/backend/ipc/register-worktree-ipc.mjs", [
    ["worktree:applyMerge", "worktree.applyMerge", "import('./app-api').TaskweaverWorktreeApi['applyMerge']", (invoke) => (taskId, options, conversationId, runId) => invoke('worktree:applyMerge', taskId, options ?? {}, conversationId ?? null, runId ?? null)],
    ["worktree:diff", "worktree.diff", "import('./app-api').TaskweaverWorktreeApi['diff']", (invoke) => (taskId, conversationId, runId) => invoke('worktree:diff', taskId, conversationId ?? null, runId ?? null)],
    ["worktree:list", "worktree.list", "import('./app-api').TaskweaverWorktreeApi['list']", (invoke) => (conversationId) => invoke('worktree:list', conversationId ?? null)],
    ["worktree:previewMerge", "worktree.previewMerge", "import('./app-api').TaskweaverWorktreeApi['previewMerge']", (invoke) => (taskId, conversationId, runId) => invoke('worktree:previewMerge', taskId, conversationId ?? null, runId ?? null)],
    ["worktree:remove", "worktree.remove", "import('./app-api').TaskweaverWorktreeApi['remove']", (invoke) => (taskId, force, conversationId, runId) => invoke('worktree:remove', taskId, force === true, conversationId ?? null, runId ?? null)],
  ]),
  ...invokeGroup("electron/backend/register-workspace-git-ipc.mjs", [
    ["workspace:createManualGitCommit", "workspace.createManualGitCommit", "import('./app-api').TaskweaverWorkspaceApi['createManualGitCommit']", (invoke) => (options) => invoke('workspace:createManualGitCommit', options)],
    ["workspace:deleteGitCheckpoint", "workspace.deleteGitCheckpoint", "import('./app-api').TaskweaverWorkspaceApi['deleteGitCheckpoint']", (invoke) => (checkpointId) => invoke('workspace:deleteGitCheckpoint', checkpointId)],
    ["workspace:getGitCheckpointDiff", "workspace.getGitCheckpointDiff", "import('./app-api').TaskweaverWorkspaceApi['getGitCheckpointDiff']", (invoke) => (checkpointId) => invoke('workspace:getGitCheckpointDiff', checkpointId)],
    ["workspace:gitStatus", "workspace.gitStatus", "import('./app-api').TaskweaverWorkspaceApi['gitStatus']", (invoke) => () => invoke('workspace:gitStatus')],
    ["workspace:gitSuggestCommit", "workspace.gitSuggestCommit", "import('./app-api').TaskweaverWorkspaceApi['gitSuggestCommit']", (invoke) => () => invoke('workspace:gitSuggestCommit')],
    ["workspace:listGitCheckpoints", "workspace.listGitCheckpoints", "import('./app-api').TaskweaverWorkspaceApi['listGitCheckpoints']", (invoke) => () => invoke('workspace:listGitCheckpoints')],
    ["workspace:openPath", "workspace.openPath", "import('./app-api').TaskweaverWorkspaceApi['openPath']", (invoke) => (relativePath) => invoke('workspace:openPath', relativePath)],
    ["workspace:previewManualGitCommit", "workspace.previewManualGitCommit", "import('./app-api').TaskweaverWorkspaceApi['previewManualGitCommit']", (invoke) => () => invoke('workspace:previewManualGitCommit')],
    ["workspace:restoreGitCheckpoint", "workspace.restoreGitCheckpoint", "import('./app-api').TaskweaverWorkspaceApi['restoreGitCheckpoint']", (invoke) => (payload) => invoke('workspace:restoreGitCheckpoint', payload)],
    ["workspace:revertDiff", "workspace.revertDiff", "import('./app-api').TaskweaverWorkspaceApi['revertDiff']", (invoke) => (payload) => invoke('workspace:revertDiff', payload)],
  ]),
  ...invokeGroup("electron/backend/ipc/register-workspace-ipc.mjs", [
    ["workspace:createReference", "workspace.createReference", "import('./app-api').TaskweaverWorkspaceApi['createReference']", (invoke) => (droppedPath) => invoke('workspace:createReference', droppedPath)],
    ["workspace:getTrust", "workspace.getTrust", "import('./app-api').TaskweaverWorkspaceApi['getTrust']", (invoke) => () => invoke('workspace:getTrust')],
    ["workspace:listContext", "workspace.listContext", "import('./app-api').TaskweaverWorkspaceApi['listContext']", (invoke) => (query, limit) => invoke('workspace:listContext', query ?? '', limit ?? 100)],
    ["workspace:saveClipboardImage", "workspace.saveClipboardImage", "import('./app-api').TaskweaverWorkspaceApi['saveClipboardImage']", (invoke) => (payload) => invoke('workspace:saveClipboardImage', payload)],
    ["workspace:setTrust", "workspace.setTrust", "import('./app-api').TaskweaverWorkspaceApi['setTrust']", (invoke) => (trusted) => invoke('workspace:setTrust', trusted)],
  ]),
]

export const INVOKE_CHANNELS = IPC_CHANNELS.map(({ name }) => name)

export const OPTIONAL_BRIDGE_NAMESPACES = Object.freeze(['pricing', 'permission', 'userQuestions', 'usage', 'openusage', 'terminal', 'portfolio', 'preferences', 'sandbox', 'webSearch', 'worktree', 'memory', 'jobs', 'github', 'debug'])


export const PRELOAD_EVENTS = Object.freeze([
  { bridgePath: 'models.onOAuthStatus', event: 'models:oauthStatus' },
  { bridgePath: 'models.onUpdateStatus', event: 'models:updateStatus' },
  { bridgePath: 'mcp.onGitHubOAuthStatus', event: 'mcp:githubOAuthStatus' },
  { bridgePath: 'chat.onMux', event: 'chat:mux' },
  { bridgePath: 'chat.onDshView', event: 'chat:dshView' },
  { bridgePath: 'chat.onStream', event: 'chat:stream' },
  { bridgePath: 'chat.onPromptBudget', event: 'chat:promptBudget' },
  { bridgePath: 'permission.onPrompt', event: 'permission:prompt' },
  { bridgePath: 'userQuestions.onPrompt', event: 'user-question:prompt' },
  { bridgePath: 'userQuestions.onResolved', event: 'user-question:resolved' },
  { bridgePath: 'terminal.onData', event: 'terminal:data' },
  { bridgePath: 'terminal.onExit', event: 'terminal:exit' },
  { bridgePath: 'sandbox.onMode', event: 'sandbox:mode' },
])

export const PRELOAD_LOCAL_METHODS = Object.freeze([
  { bridgePath: 'workspace.getDroppedFilePath', create: (webUtils) => (file) => webUtils.getPathForFile(file) },
])

export const renderPreloadEventSubscription = (event) => `(listener) => {
  const handler = (_event, payload) => listener(payload)
  ipcRenderer.on(${JSON.stringify(event)}, handler)
  return () => ipcRenderer.removeListener(${JSON.stringify(event)}, handler)
}`
