/* Generated by @z/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@z/dsh-typert-protocol'
import type { EncodedImageAttachment } from '@z/dsh-attachment/types'
import type { CommandDescriptor, CommandExecution } from '@z/dsh-commands/types'
import type { SessionId } from '@z/dsh-session/types'

declare module '@z/dsh-typert-protocol' {
  interface TypertRemoteNamespace$636f6d6d616e6473 {
    execute: (agentId: SessionId, line: string, images: readonly EncodedImageAttachment[], signal?: AbortSignal) => Promise<RemoteResult<CommandExecution | undefined>>
    list: (agentId: SessionId) => Promise<RemoteResult<readonly CommandDescriptor[]>>
  }
  interface TypertRemoteMap {
    'commands/execute': (agentId: SessionId, line: string, images: readonly EncodedImageAttachment[], signal?: AbortSignal) => Promise<RemoteResult<CommandExecution | undefined>>
    'commands/list': (agentId: SessionId) => Promise<RemoteResult<readonly CommandDescriptor[]>>
  }
  interface TypertRemoteNamespaceMap {
    'commands': TypertRemoteNamespace$636f6d6d616e6473
  }
  interface TypertRemoteScopeMap {
    'agent:commands/execute': (line: string, images: readonly EncodedImageAttachment[], signal?: AbortSignal) => Promise<RemoteResult<CommandExecution | undefined>>
    'agent:commands/list': () => Promise<RemoteResult<readonly CommandDescriptor[]>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
